### ISSUE TITLE
Kills Achievements

### ISSUE THREAD

**Issue by MinePlayGamer** [PyvesB/advanced-achievements#1002]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.1
* Minecraft version: 1.8
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: MinePlay_01

:question: **I need help to create a Specify Entity killer achievement**

Hello!
So I need to create an achievement that indicates when a specific player is killed, but when I create it doesn't count progress, how do I make it work?

Thank you for help me.

:wrench: **Configuration**

````
Kills:
  specificplayer-6adf8113-0e9b-41c0-a7e6-d5dada0cfef8:
    '1':
      Goal: Matar o Oficial zHenri_ 1 vez.
      Message: Você matou o Oficial zHenri_.
      Name: kills_1_zhenri
      DisplayName: Teste
````

**Comment by PyvesB** [comment]
Hello @MinePlayGamer ! 👋🏻 

Do the players have the right permissions? I believe they need to have both `achievement.count.kills` and `achievement.count.kills.specificplayer-6adf8113-0e9b-41c0-a7e6-d5dada0cfef8` in this case. 😉

**Comment by MinePlayGamer** [comment]
I was testing with Op.

**Comment by PyvesB** [comment]
Can you reproduce with only Advanced Achievements enabled on your server, and no other plugin?

**Comment by MinePlayGamer** [comment]
No, I am using Vault, IConomy and Advanced Plugins.

**Comment by PyvesB** [comment]
Well, in that case I suggest progressively re-adding your other plugins. When things break again in Advanced Achievements, that will point to the one causing conflicts. 😉

**Comment by PyvesB** [comment]
No news for a couple of weeks, I'm assuming the above suggestions helped you find the faulty plugin, therefore closing the issue.
