### ISSUE TITLE
Multi items for one achievements

### ISSUE THREAD

**Issue by Slodrein** [PyvesB/advanced-achievements#1004]
:information_source: **Basic information**

* Advanced Achievements version: 7.0.3
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Slodrein

:question: **Help request**

My question is how to put several items for a single achievement ?

**Comment by PyvesB** [comment]
Hello @Slodrein ! 👋🏻 

The question is somewhat unclear - are you talking about item rewards?

**Comment by Slodrein** [comment]
Hi @PyvesB 

No for example : 

`**oak_log**and **spruce_log**:
    1024:
      Goal: Casser 1024 Bûches de Bois.
      Message: §6Vous avez cassé 1024 bûches de bois!
      Name: break_1024_bbois
      DisplayName: Le Bûcheron I !
      Type: normal`

1 achievement for 2 breaking items

**Comment by PyvesB** [comment]
Okay. You'll probably find this Wiki page helpful: https://github.com/PyvesB/advanced-achievements/wiki/FAQ-(Frequently-Asked-Questions)#3-how-can-i-track-multiple-types-for-categories-with-sub-categories-places-kills-targetsshot-breaks-crafts-breeding-playercommands-jobsreborn

**Comment by Slodrein** [comment]
Oh ! I'm so sorry ! thank's man !

**Comment by PyvesB** [comment]
No worries, closing the issue then. :)
