### ISSUE TITLE
How to I delete categories and adchievements?

### ISSUE THREAD

**Issue by Zefix0509** [PyvesB/advanced-achievements#1010]
Hello,

I don't know why but when I delete some adchivements and categories in config.yml and gui.yml after that I /aach reload and they seems to rewrite them in the config files. I want to delete them!

**Comment by PyvesB** [comment]
Hello @Zefix0509 ! 👋🏻 

I believe the following message will answer your question: https://github.com/PyvesB/advanced-achievements/pull/979#pullrequestreview-611052956 😉

**Comment by Zefix0509** [comment]
is it possible to disable them in the configuration file?

**Comment by PyvesB** [comment]
Please read the provided link.

**Comment by Zefix0509** [comment]
ok ty and I do I disable a achievement/advancement?

**Comment by PyvesB** [comment]
To disable a specific achievement, simply remove its configuration lines from _config.yml_. To delete an advancement, you'll need to re-run _/aach generate_.
