### ISSUE TITLE
Custom achievements not showing up and default achievements not being removed.

### ISSUE THREAD

**Issue by Viictiri** [PyvesB/advanced-achievements#1011]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.1
* Minecraft version: 1.16.4
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Viictiri

:question: **Help request**

I’m currently trying to make custom achievements for a server I’m working on, but every time I make an achievement, save, and then reload in Minecraft, the achievements don't show up. I’ve gotten it to work once, but never again after that. The same goes for removing achievements, I’ve tried removing the Mario achievement but it hasn’t gone away. Am I possibly putting in the code wrong? 

:wrench: **Configuration**

````
Kills:
  creeper:
    1:
      Goal: Kill a creeper.
      Message: The first time you killed a creeper!
      Name: kills_1_creeper
      DisplayName: Boom! Boom! Boom
      Type: normal
      Reward:
        Money: 1
  skeleton:
    1:
      Goal: Kill a skeleton.
      Message: The first time you killed a skeleton!
      Name: kills_1_skeleton
      DisplayName: Bone Appetit
      Type: normal
      Reward:
        Money: 1

````

**Comment by PyvesB** [comment]
Hello @Viictiri ! 👋🏻 

Coul you please share your full configuration so that I can have a look?

**Comment by Viictiri** [comment]
Yup! Also nothing in the GUI was changed. I'm very new to Advanced Achievements so I'm sorry if this is a stupid problem.
`#==============================O==============================#
# I---------------------------------------------------------I #
# |   Advanced Achievements ${project.version} configuration - Readme   | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# Only spaces, NO tabs. Don't forget the indents (2 spaces per indentation level).
# To check syntax errors in your file, use: https://yaml-online-parser.appspot.com
# Default config: https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml
# If you want to help the project, feel free to check our GitHub: https://github.com/PyvesB/advanced-achievements
# Visit the wiki for some valuable additional documentation: https://github.com/PyvesB/advanced-achievements/wiki
# For donations use: https://www.paypal.com/cgi-bin/webscr?hosted_button_id=7KTQYC4YT52NQ&cmd=_s-xclick

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#

# Time in seconds between each /aach book (unless user has permission achievement.*).
TimeBook: 900

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Set to true to activate firework effects when a player receives an achievement.
Firework: true

# Choose ball_large, ball, burst, creeper, star or random.
FireworkStyle: ball_large

# Set to true to activate simpler effects and a calm sound when a player receives an achievement.
# Ignored if Firework setting is set to true.
SimplifiedReception: false

# Number of players displayed in /aach top, week and month commands.
TopList: 5

# Set to true to activate particle effects when performing /aach book, /aach stats with all achievements and
# /aach top, week or month when ranked in the top list.
AdditionalEffects: true

# Set to true to activate sounds when performing /aach book, /aach stats with all achievements and /aach top, 
# week or month when ranked in the top list.
Sound: true

# For /aach book. Possible values: github.com/PyvesB/advanced-achievements/wiki/Sound-names
SoundBook: entity_player_levelup

# For /aach stats with all achievements. Possible values: github.com/PyvesB/advanced-achievements/wiki/Sound-names
SoundStats: entity_firework_rocket_blast

# For /aach top, week, month when ranked in the top list. Possible values: github.com/PyvesB/advanced-achievements/wiki/Sound-names
SoundRanking: entity_firework_rocket_blast

# Set the icon of the plugin (default: shamrock, \u2618).
Icon: \u2618

# Set the color of the plugin (default: 5, dark purple).
Color: 5

# Notify other connected players when an achievement is received.
# This defines the default behaviour, a player can override what he sees by using /aach toggle.
NotifyOtherPlayers: false

# When NotifyOtherPlayers is enabled, notifications are done using action bars when ActionBarNotify is true.
# When ActionBarNotify is false, chat messages are used.
ActionBarNotify: true

# Display achievement DisplayName and Message as screen titles. Ignored if using Minecraft 1.7.9 or 1.7.10.
TitleScreen: true

# Display chat messages when a player receives an achievement.
ReceiverChatMessages: true

# When a player receives an achievement, the DisplayName, Message and rewards of the achievement are displayed in
# the chat. If HoverableReceiverChatText is true, a single hoverable text will be displayed to the receiver.
# Otherwise texts will be displayed one after the other.
HoverableReceiverChatText: false

# Separator between name, description and date on a book page.
BookSeparator: ""

# Set the format of the achievement name in /aach list (default: "%ICON% %NAME% %ICON%").
ListAchievementFormat: "%ICON% %NAME% %ICON%"

# Set the format of the header used for most chat messages (default: "§7[%ICON%§7]").
ChatHeader: "§7[%ICON%§7]"

# Stop all stats from increasing when player in creative mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-creative mode.
RestrictCreative: false

# Stop all stats from increasing when player in spectator mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-spectator mode.
# No effect if using Minecraft 1.7.9 or 1.7.10.
RestrictSpectator: true

# Stop all stats from increasing when player in adventure mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-adventure mode.
RestrictAdventure: false

# Stop all stats from increasing when player in a specific world, including PlayedTime (delete the [] before adding values).
# Connection achievements will only be handled once a player enters a non-excluded world.
ExcludedWorlds: []
#  - yourWorld1
#  - yourWorld2

# Ignore vertical dimension (Y axis) when calculating distance statistics.
IgnoreVerticalDistance: false

# Don't show these categories in the achievement GUI or in the stats output.
# Also prevent obtaining achievements for these categories and prevent stats from increasing.
DisabledCategories:
- AdvancementsCompleted

# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: false

# For categories with a series of related achievements where the only thing changing is the number of times
# the event has occurred, show achievements that have been obtained and show the next obtainable achievement,
# but obfuscate the additional achievements. For example, under Places, stone, the first achievement could have a
# target of 100 stone, the second 500 stone, and the third 1000 stone.  When ObfuscateProgressiveAchievements
# is true, initially only the 100 stone achievement will be readable in the GUI.  Once 100 stone have been placed,
# the 500 stone achievement will become legible.
ObfuscateProgressiveAchievements: false

# Similar to ObfuscateProgressiveAchievements, but displays not received achievements as locked in /aach list.
HideProgressiveAchievements: false

# Hide categories for which a player has not yet received achievements by displaying them as locked in /aach list.
HideNotReceivedCategories: false

# Completely hide categories for which the player does not have the corresponding count permissions.
HideNoPermissionCategories: false

# Hide the reward display in /aach list.
HideRewardDisplayInList: false

# Display precise statistic information in the /aach list progress bars.
EnrichedListProgressBars: true

# Annotate each achievement displayed in a /aach list category with a number.
NumberedItemsInList: false

# Color used for not yet received achievements in /aach list.
ListColorNotReceived: 8

# Italicise not yet received achievements in /aach list. Obfuscated achievements are not affected.
ListItaliciseNotReceived: true

# Sort pages of the book in chronological order (false for reverse chronological order).
BookChronologicalOrder: true

# Do not take into account items broken with Silk Touch for the Breaks achievements.
DisableSilkTouchBreaks: false

# Do not take into account ores broken with Silk Touch for the Breaks achievements.
# DisableSilkTouchBreaks takes precedence over this. Not applicable to iron or gold ores.
DisableSilkTouchOreBreaks: false

# Language file to use. Available: lang.yml, lang-BP.yml, lang-CN.yml, lang-CZ.yml, lang-DE.yml, lang-ES.yml, lang-FI.yml
# lang-FR.yml, lang-HU.yml, lang-IT.yml, lang-PL.yml, lang-RO.yml, lang-RU.yml, lang-SE.yml, lang-TR.yml, lang-TW.yml, lang-VN.yml
LanguageFileName: lang.yml

# Time in seconds between each statistic count. Only the listed categories are currently supported.
StatisticCooldown:
  LavaBuckets: 10
  WaterBuckets: 10
  Milk: 10
  Beds: 30
  Brewing: 5
  MusicDiscs: 30

# Display action bar message when player performs an action while in the cooldown period.
# No effect if using Minecraft 1.7.9 or 1.7.10.
CooldownActionBar: true

# Locale used to format dates in /aach book and /aach list. You must select an ISO 639 language code.
# The list of possible language codes can be found at www.loc.gov/standards/iso639-2/php/code_list.php
DateLocale: en

# Display reception time of achievements in /aach book and /aach list in addition to the date. For achievements
# received in plugin versions prior to 3.0, the precise time information is not available and will be displayed as midnight.
DateDisplayTime: true

# Register advancements with a description corresponding to the Goal parameter of each achievement.
# If changed, run /aach generate to regenerate advancements with the new parameter value taken into account.
# No effect if using Minecraft versions prior to 1.12.
RegisterAdvancementDescriptions: true

# If true, hide advancements from the advancement GUI. Advancement notifications will still appear when receiving achievements.
# No effect if using Minecraft versions prior to 1.12.
HideAdvancements: false

# If true, PlayedTime will no longer increase when the player is AFK. Requires Essentials to work.
IgnoreAFKPlayedTime: false

# Awarded when a player has received all the achievements. Use the same reward pattern as with achievements.
# See https://github.com/PyvesB/advanced-achievements/wiki/Rewards
AllAchievementsReceivedRewards:
  IncreaseMaxOxygen: 30
  Experience: 100

# Title shown on the root advancement.
RootAdvancementTitle: Advanced Achievements

# Background shown on the Advanced Achievements advancement tab.
# Must be a resource location to any image in a resource pack.
AdvancementsBackground: "minecraft:textures/item/book.png"

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#

# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: true

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: h2

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ""
  
# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ""

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: "jdbc:mysql://localhost:3306/minecraft"
DatabaseUser: root
DatabasePassword: root
  
#============================OO=OO============================#
# IV-------------------------------------------------------IV #
# |                  Performance settings                   | #
# |        Change only if you are an experienced user       | #
# 4---------------------------------------------------------4 #
#============================oo=oo============================#

# Frequency of play time checks for players (seconds). Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 60

# Calculates distance traveled by players (seconds). Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 5

# Frequency of some statistics writes to the database (seconds). Do a full server restart, and not just /aach reload.
PooledRequestsTaskInterval: 10

#============================OOOOO============================#
# V---------------------------------------------------------V #
# |              Multiple action achievements               | #
# |       These require sub-categories and thresholds       | #
# 5---------------------------------------------------------5 #
#============================ooooo============================#

# When a specific block is placed (available names: github.com/PyvesB/advanced-achievements/wiki/Material-names).
Places:  
  chest:
    5:
      # Optional, used in /aach list when achievement not yet received, and in advancements.
      Goal: Place 5 chests.
      # Description; displayed when receiving achievement, and in /aach book and /aach list.
      Message: §6You have placed 5 chests!
      # Database name, must also be used in /aach delete and /aach check.
      Name: place_5_chest
      # Displayed when receiving achievement, and in /aach book and /aach list.
      DisplayName: Storage Expert
    50:
      Goal: Place 50 chests.
      Message: §6You have placed 50 chests!
      Name: place_50_chest
      DisplayName: Tetris Master
  stone:
    100:
      Goal: Place 100 Stones.
      Message: One hundred placed stones!
      Name: place_100_stone
      DisplayName: Stone Addict
    1000:
      Goal: Place 1000 stones.
      Message: One thousand placed stones!
      Name: place_1000_stone
      DisplayName: Stone God
      Reward:
        Command:
          Execute: "say §7ALERT: §4PLAYER§7 has become the §4STONE GOD§7!"
          Display: Become the Stone God!

# When a specific block is broken (available names: github.com/PyvesB/advanced-achievements/wiki/Material-names).
# You can use notations such as sand:1 for pre-1.13 versions, which means sand item with metadata 1 (red sand).
Breaks: 
  ice:
    10:
      Goal: Break 10 ice blocks.
      Message: You have broken 10 ice blocks!
      Name: break_10_ice
      DisplayName: Cold Drink Supplier
  # Use the following construct to track multiple types. Note that if ever you add/remove a type grouped to others with |,
  # progress for this sub-category group will start back at 0.
  snow|snow_block|ice:
    32:
      Goal: Break 32 ice and/or snow.
      Message: You have broken 32 ice and snow, Woo!
      Name: break_32_ice_any
      DisplayName: Praying for Summer
  stone:
    1:
      Goal: Break a block.
      Message: §1The first time you went mining!
      Name: break_1_stone
      DisplayName: Cobble Gobble!
      # Use semicolons for multiple command rewards. PLAYER will be replaced by players name.
      Reward:
        Command:
          Execute: give PLAYER dispenser 10; give PLAYER lever 5

# When "something" is killed. You can use any of the following:
# - an entity type (available names: github.com/PyvesB/advanced-achievements/wiki/Entity-names).
# - poweredcreeper.
# - a mob's custom name (name tag/plugins such as Mythic Mobs) for Minecraft 1.8 or more recent.
# - player to track player kills as a whole.
# - specificplayer- followed by player UUID to track how many times a specific player has been killed.
Kills:
  zombie:
    1:
      Goal: Kill a zombie.
      Message: The first time you killed a zombie!
      Name: kills_1_zombie
      DisplayName: The Walking Dead
      Reward:
        Money: 1         
        Item: diamond 1
  creeper:
    1:
      Goal: Kill a creeper.
      Message: The first time you killed a creeper!
      Name: kills_1_creeper
      DisplayName: Boom! Boom! Boom
      Type: normal
      Reward:
        Money: 1
  skeleton:
    1:
      Goal: Kill a skeleton.
      Message: The first time you killed a skeleton!
      Name: kills_1_skeleton
      DisplayName: Bone Appetit
      Type: normal
      Reward:
        Money: 1
  # Mythic Mobs 'Display' parameter. Change & to §.
  §2Skeletal Knight:
    1:
      Goal: Kill the evil Skeletal Knight.
      Message: §eYou killed a Mythic Mob!
      Name: kills_1_skeletal_night
      DisplayName: Mythic Killer
  specificplayer-56c79b19-4500-466c-94ea-514a755fdd09:
    1:
      Goal: Kill the evil Author.
      Message: Yippie! You killed the author of the plugin!
      Name: kills_1_darkpyves
      DisplayName:  No More DarkPyves
      Reward:
        IncreaseMaxHealth: 1
          
# When a specific target is shot (but not necessarily killed) with a projectile.
# Available target block names: github.com/PyvesB/advanced-achievements/wiki/Material-names
# Available target entity names: github.com/PyvesB/advanced-achievements/wiki/Entity-names
TargetsShot:
  villager:
    10:
      Goal: Throw things at villagers.
      Message: You lapidated villagers 10 times.
      Name: targetsshot_10_villager
      DisplayName: The Stoner
  glass:
    100:
      Goal: Try to break granny's windows.
      Message: You shot 100 projectiles at glass blocks!
      Name: targetsshot_100_glass
      DisplayName: Window Breaker

# When a specific item is crafted (available names: github.com/PyvesB/advanced-achievements/wiki/Material-names).
Crafts:
  iron_sword:
    1:      
      Goal: Craft a sword.
      Message: The first time you crafted a blade!
      Name: craft_1_blade
      DisplayName: Blacksmith Apprentice
      Reward:
        Money: 2
  diamond_sword:
    1:      
      Goal: Craft 1 diamond sword.
      Message: Next craft, Excalibur?
      Name: craft_1_diamond_blade
      DisplayName: Blacksmith Legend
      Reward:
        Experience: 500
        
# When a player enters a specific command (specify command prefixes in lower case without initial slash).
# For instance a command /awf add world from the AntiWorldFly plugin matches with subcategory 'awf add'.
# Aliases of a given command will also be taken into account.
PlayerCommands:
  aach stats:
    10:
      Goal: Check your stats 10x.
      Message: Run the stats command 10 times!
      Name: playercommand_aachstats_10
      DisplayName: Statistician
      Rewards:
        Commands:
          Execute: say §7PLAYER is now a statistician
          Display: Broadcast
          
# When animals breed (available names: github.com/PyvesB/advanced-achievements/wiki/Entity-names).
Breeding:
  sheep:
    1:
      Goal: Breed a sheep.
      Message: You bred your first sheep!
      Name: breeding_1_sheep
      DisplayName: Breeder
      
#===========================OOO=OOO===========================#
# VI-------------------------------------------------------VI #
# |               Normal action achievements                | #
# |           These are based on thresholds only            | #
# 6---------------------------------------------------------6 #
#===========================ooo=ooo===========================#

# When a player connects during the day; statistic increases at most once per day.
Connections:
  1:
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice

# When the player dies.
Deaths:
  1:
    Goal: You have to Die.
    Message: The first time you died!
    Name: deaths_1
    DisplayName: Rest in Peace
    Reward:
        # Text after the material and quantity is interpreted as a custom name, shown in /aach list and when receiving the reward.
        Item: stone 5 Tombstone
    
# When an arrow is shot.
Arrows:
  10:
    Goal: Shoot 10 arrows.
    Message: 10 arrows shot!
    Name: arrows_10
    DisplayName: Arrows Around the Place
  10:
    Goal: Shoot 50 arrows.
    Message: 50 arrows shot!
    Name: arrows_50
    DisplayName: Robin Hood!
    
# When a snowball is thrown.  
Snowballs:
  1000:
    Goal: Throw 1000 snowballs.
    Message: 1000 snowballs thrown. That's the spirit!
    Name: snowballs_1000
    DisplayName: Winter Addict 
    Reward:
        # 30 corresponds to one bubble in the oxygen bar.
        IncreaseMaxOxygen: 30
    
# When an egg is thrown.  
Eggs:
  1000:
    Goal: Throw 1000 eggs.
    Message: 1000 eggs thrown!
    Name: eggs_1000
    DisplayName: Omelet Addict 
    
# When a fish is caught. 
Fish:
  1:
    Goal: Fish a fish.
    Message: The first time you caught a fish!
    Name: fish_1
    DisplayName: Time for Fish and Chips

# When a tool/armor/weapon is broken.  
ItemBreaks:
  1:
    Goal: Let an item break.
    Message: You broke your favorite tool!
    Name: itembreaks_1
    DisplayName: §4Clumsy Guy

# When an item is eaten (excludes potions and milk).
EatenItems:
  1:
    Goal: Eat something.
    Message: Just had a snack!
    Name: eatenitems_1
    DisplayName: First Snack  
  5:
    Goal: Eat a nice meal.
    Message: First feast
    Name: eatenitems_5
    DisplayName: Five Course Meal  
    
# When a sheep is sheared.
Shear:
  100:
    Goal: Shear 100 sheep.
    Message: 100 sheep sheared!
    Name: shear_100
    DisplayName: §1Wool Addict

# When a cow is milked.
Milk:
  1:
    Goal: Milk a cow.
    Message: §eJust milked a cow!.... §cMOOW
    Name: milk_1
    DisplayName: First Milk
    Reward:
      Experience: 100
    
# When a bucket is filled with lava.
LavaBuckets:
  10:
    Goal: Fill 10 buckets with lava.
    Message: 10 buckets filled with lava!
    Name: lavabuckets_10
    DisplayName: Pyroman
    
# When a bucket is filled with water.
WaterBuckets:
  15:
    Goal: Fill 10 buckets with water.
    Message: 15 buckets filled with water!
    Name: waterbuckets_15
    DisplayName: Fireman    
    
# When an anvil is used.
AnvilsUsed:
  1:
    Goal: Repair an item.
    Message: You just repaired your first item!
    Name: anvilsused_1
    DisplayName: First Repair 
    
# When an enchantment is performed.
Enchantments:
  5:
    Goal: Enchant 5 things.
    Message: 5 objects enchanted!
    Name: enchantments_5
    DisplayName: §5Enchanter
    
# When a bed is entered. 
Beds:  
  5:
    Goal: Sleep 5 times.
    Message: You entered a bed 5 times!
    Name: bed_5
    DisplayName: Sleepy Guy 
    
# Maximum level reached.    
MaxLevel:  
  10:
    Goal: Reach level 10.
    Message: Level 10 reached!
    Name: maxlevel_10
    DisplayName: §4Rookie
    
# When a potion is consumed.
ConsumedPotions:
  100:
    Goal: Drink 100 potions.
    Message: Drinking weird beverages all the time...
    Name: consumedpotions_100
    DisplayName: You thirsty? 
    
# Amount of time played on the server (in hours, use integers).
PlayedTime:
  1:
    Goal: Play an hour.
    Message: You played for one hour on the server!
    Name: playedtime_1
    DisplayName: First Hour
    
# When a distance is traveled by foot.
DistanceFoot:
  1000:
    Goal: Travel 1000 Blocks with your feet.
    Message: You traveled 1000 blocks by foot!
    Name: distancefoot_1000
    DisplayName: Big Walker 
    
# When a distance is traveled in a minecart.
DistanceMinecart:
  100:
    Goal: Travel 100 Blocks with a minecart.
    Message: You traveled 100 blocks in a minecart!
    Name: distanceminecart_100
    DisplayName: Carting Fan

# When an item is dropped on the ground.
ItemDrops:
  15:
    Goal: Drop 15 items.
    Message: §cYou're killing the planet!
    Name: itemdrops_15
    DisplayName: Polluter
    
# When an item is picked up from the ground.
ItemPickups:
  40:
    Goal: Pick 40 items up.
    Message: You're saving the planet!
    Name: itempickups_40
    DisplayName: Environmentalist
    
# When soil is plowed with a hoe.
HoePlowings:
  10:
    Goal: Plow 10 times.
    Message: You plowed the ground 10 times!
    Name: hoeplowings_10
    DisplayName: Farmer
    Reward:                 
        Item: cookie 15
    
# When bone meal is used to fertilise plants.
Fertilising:
  15:
    Goal: Use bonemeal 15 times.
    Message: You used bone meal on plants 15 times!
    Name: fertilising_15
    DisplayName: Gardener
    
# When an animal is tamed.
Taming:
  1:
    Goal: Tame an animal.
    Message: You tamed your first animal!
    Name: taming_1
    DisplayName: Tamer

# When a potion is brewed.
Brewing:
  1:
    Goal: Brew a potion.
    Message: You brewed your first potion!
    Name: brewing_1
    DisplayName: Alchemist
    
# When a firework is launched.
Fireworks:
  10:
    Goal: Launch fireworks 10 times.
    Message: You launched 10 fireworks!
    Name: fireworks_10
    DisplayName: Pyrotechnist
    Reward:
      Experience: 200

# When a music disc is played.
MusicDiscs:
  1:
    Goal: Use a jukebox.
    Message: One jukebox used!
    Name: musicdiscs_1
    DisplayName: DJ

# When a player teleports with an enderpearl.
EnderPearls:
  10:
    Goal: Teleport with ender pearls 10 times.
    Message: 10 teleportations with ender pearls!
    Name: enderpearls_10
    DisplayName: Teleport Man
    
# When a player gives a pet to another player (requires Pet Master plugin version 1.4 or above).
PetMasterGive:
  3:
    Goal: Give 3 pets to friends.
    Message: 3 pets given to friends!
    Name: petmastergive_3
    DisplayName: Donator

# When a player receives a pet from another player (requires Pet Master plugin version 1.4 or above).
PetMasterReceive:
  10:
    Goal: Receive 10 pets.
    Message: 10 pets received from friends!
    Name: petmasterreceive_10
    DisplayName: Receiver
    
# When an item is smelt in a furnace.
Smelting:
  250:
    Goal: Smelt 250 items.
    Message: 250 items smelt in a furnace!
    Name: smeltitems_250
    DisplayName: The Smelter

# When riptide is used with a trident.
Riptides:
  1:
    Goal: Use a magical trident.
    Message: You've mastered the powers of the sea!
    Name: riptides_1
    DisplayName: Poseidon
# When an a certain amount of advancements are completed.
AdvancementsCompleted:
  20:
    Goal: Complete 20 advancements.
    Message: 20 advancements completed!
    Name: advancements_20
    DisplayName: Game Block Advance
    # Use semicolons for multiple item rewards as well. The below example will reward 8 diamond and 1 cake
    Reward:
      Item: diamond 8; cake 1
  
#===========================OOOOOOO===========================#
# VII-----------------------------------------------------VII #
# |               Command-based achievements                | #
# 7---------------------------------------------------------7 #
#===========================ooooooo===========================#
    
# Allow Commands achievement to be awarded several times.
MultiCommand: true
    
# A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
# yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
Commands:
  yourAch1:
    Goal: Take part in the special event!\nEvery Friday at 8pm!
    Message: You took part in the special event!
    Name: your_ach1
    DisplayName: Special Event Achievement!
    
# When the command /aach add is called for this category.
Custom:
  votes:
    10:
      Message: Voted 10 times for the server!
      Name: customs_votes_10
      DisplayName: Server fan
      Reward:
        Money: 5
    
#==========================OOOO=OOOO==========================#
# VIII-------------------------0-------------------------VIII #
# |  Parameters in future plugin versions will appear here  | #
# 8----------------------------0----------------------------8 #
#==========================oooo=oooo==========================#`

**Comment by PyvesB** [comment]
Well, there is no Mario achievement in the configuration you shared, and no Mario achievement either when I try using old Advanced Achievements version 6.2.1 with your configuration on my own server.

Please make sure you're definitely editing and saving the right configuration file (and not a copy that was made somewhere else for example), and that you run _/aach reload_ when you're done.

**Comment by Viictiri** [comment]
Alright! I’ll check and make sure everything is saving properly. Thank you for your time!!

**Comment by PyvesB** [comment]
Will close this for now, but feel free to ping me or open a new issue if you encounter any other problems! :)
