### ISSUE TITLE
earning Achievements I shouldn't have

### ISSUE THREAD

**Issue by SirCraftypants** [PyvesB/advanced-achievements#1015]
:information_source: **Basic information**

* Advanced Achievements version: 7.0.6
* Minecraft version: Paper 1.16.5
* Wiki read: Yes
* Existing issues searched: Not that i can see
* Spigot username: Sir_Craftypants

:beetle: **Description**

Just logged on as Op, got 4 Achievements i shouldn't have got because i hadn't even completed 50 achievements!
![2021-05-12](https://user-images.githubusercontent.com/66942713/118019064-76fd4f00-b350-11eb-8bab-af62e45b7598.png)

`# When an a certain amount of advancements are completed.
AdvancementsCompleted:
  '50':
    Goal: Complete 50 advancements.
    Message: 50 advancements completed!
    Name: advancements_50
    DisplayName: Making Progress
    Reward:
      Experience: 500
      Command:
        Execute: eco give PLAYER 500
        Display: 500 Coin   
  '100':
    Goal: Complete 100 advancements.
    Message: 100 advancements completed!
    Name: advancements_100
    DisplayName: Advancement Expert
    Reward:
      Experience: 1000
      Command:
        Execute: eco give PLAYER 1000
        Display: 1000 Coin            
  '200':
    Goal: Complete 200 advancements.
    Message: 200 advancements completed!
    Name: advancements_200
    DisplayName: Advancement Expert
    Reward:
      Experience: 2000
      Command:
        Execute: eco give PLAYER 2000
        Display: 2000 Coin      
  '300':
    Goal: Complete 300 advancements.
    Message: 300 advancements completed!
    Name: advancements_300
    DisplayName: Advancement Master
    Reward:
      Experience: 3000
      Command:
        Execute: eco give PLAYER 3000
        Display: 3000 Coin      `

Report i do not even have 50 achievements completed.

**Comment by PyvesB** [comment]
Hello @SirCraftypants ! 👋🏻

Are you sure you've read the [Wiki](https://github.com/PyvesB/advanced-achievements/wiki/FAQ-(Frequently-Asked-Questions)#4-whats-the-difference-between-an-achievement-and-an-advancement)? You seem to be confusing achievements and advancements, which are two different things. 😉

**Comment by SirCraftypants** [comment]
sorry my mistake, i meant advancements, i these particular advancements i'm not supposed to achieve until i've completed 50/100/200/300 advancements correct? I've barely completed 50 advancements and i just got all of them one after the other.

**Comment by PyvesB** [comment]
The `AdvancementsCompleted` category takes all advancements into account, including the Vanilla ones or ones created by other plugins. I'm guessing that's probably the root of the problem here.

**Comment by SirCraftypants** [comment]
ah ok, thanks for clearing that up.

**Comment by PyvesB** [comment]
No worries! There's also a little more information in #914.

**Comment by SirCraftypants** [comment]
> 
> 
> No worries! There's also a little more information in #914.

Ok the more i read the more confused i get with this.

Minecraft has achievements and advancements right? when i google it says minecraft has 107 achievements and 80 advancements.  Are these both one in the same?

If so how can i have completed 300 advancements, as mentioned before i have barely completed 50. 

Really confusing.

Unless i can find out how it works, does it count achievements or advancements, and how many does minecraft have so i can configure these properly, then i think i'm just going to have to not use the category at all.

**Comment by PyvesB** [comment]
Minecraft had achievements before 1.12, advancements after 1.12.

`AdvancementsCompleted` counts all advancements.

**Comment by SirCraftypants** [comment]
> 
> 
> Minecraft had achievements before 1.12, advancements after 1.12.
> 
> `AdvancementsCompleted` counts all advancements.

OK so google, i know not 100 reliable but, google says minecraft has 80 advancements, so lets say hypothetically speaking that i've completed all 80. 

I have no other plugins for advancements other than Advanced Achievements, i've just checked and I've completed 47 Advancements with the plugin. That only equates to 127 advancements so i don't understand how i could have achieved these advancements i reported. the plugin only has 372 advancements at present, i would have had to complete over half of them to unlock 200 and 300 but i have not?

**Comment by PyvesB** [comment]
Other plugins may add their own advancements, and maybe you've configured some custom ones as well.

For example, the user in #914 states that he's got 927 advancements in total on his server.

**Comment by SirCraftypants** [comment]
suppose i have 67 developers to contact then to find out how many advancements they have hiding in their plugins. thanks
