### ISSUE TITLE
Allow users to disable the title screen / chat messages when they get an achievement

### ISSUE THREAD

**Issue by galexrt** [PyvesB/advanced-achievements#1016]
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Galexrt

:clipboard: **Description**

A way for users to disable the title screen and / or chat messages for when they get an achievement.
We have some users which like to see the title screen, but some players don't. I haven't found a way for users to toggle it as they want.

**Comment by PyvesB** [comment]
Hello @galexrt ! 👋🏻 

Would a permission work? Specific users users could then toggle the behaviour by enabling or disabling the permission node.

**Comment by galexrt** [comment]
@PyvesB Yeah, a permission sounds good.
