### ISSUE TITLE
BlockFertilizeEvent Error

### ISSUE THREAD

**Issue by coco0325** [PyvesB/advanced-achievements#1020]
:information_source: **Basic information**

* Advanced Achievements version: 7.0.5, 7.0.6
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: coco0325

:beetle: **Description**
Error

:page_facing_up: **Server logs**

https://pastebin.com/wuBmtGdG

**Comment by PyvesB** [comment]
Hello @coco0325 ! 👋🏻 

Thanks for reporting, this should now be fixed.
