### ISSUE TITLE
vanilla achievements

### ISSUE THREAD

**Issue by MrBrights** [PyvesB/advanced-achievements#1022]
:information_source: **Basic information**

* Advanced Achievements version: true
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: bob788520

:question: **Help request**

How to disable the display of vanilla achievements?
I have set "RegisterAdvancementDescriptions:" to "false" and "HideAdvancements:" to "false", but not only did I not disable the vanilla achievement, but the message of obtaining the achievement will pop up every time I enter the server. please help me.

**Comment by PyvesB** [comment]
Hello @MrBrights ! 👋🏻 

Vanilla achievements do not exist on Minecraft 1.16.5, they were removed all the way back in Minecraft 1.12. I'm guessing you made a mistake with the server version?

Note that this is this repository is dedicated to Advanced Achievements. Asking for help for Vanilla features is off-topic, and would be best suited for the Spigot forums. 😉

**Comment by MrBrights** [comment]
![image](https://user-images.githubusercontent.com/84629656/119231112-bba79800-bb51-11eb-909d-ee8a6857c2e7.png)
I mean the default achievement displayed by pressing the "L" key. Is there a way to turn this off?
Otherwise, every time you log in, a lot of completed achievements will pop up. Is there a way to turn off these things?
I only need "/aach list"
![image](https://user-images.githubusercontent.com/84629656/119231153-e42f9200-bb51-11eb-9367-286c17e9ea35.png)

**Comment by MrBrights** [comment]
Also, if the reward content is added to the Command, the color of the "reward" string will be modified. It seems to be modified with the "ListColorNotReceived" setting, not with the "lang.yml" file

**Comment by MrBrights** [comment]
@PyvesB 
One more thing, if the commands is added to the reward, the color of the "reward" string will be modified. It seems to be modified with the "ListColorNotReceived" setting, not with the "lang.yml" file.

**Comment by PyvesB** [comment]
Are you talking about _advancements_?



> * [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
> 
> * [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

There is precisely covered in the Wiki, as well as several duplicated issues. I'm unsure how you missed them. :')

**Comment by PyvesB** [comment]
As I haven't heard back, I'll assume that the Wiki and other issues on this matter gave all the answers you were looking for, therefore closing. Feel free to open a new issue if anything else comes up! 😉
