### ISSUE TITLE
Question regarding the 1.17 update

### ISSUE THREAD

**Issue by KingOfMyGames** [PyvesB/advanced-achievements#1026]
Hey, I have a question regarding the upcoming 1.17 update. I would like to try this out on our small server, but before I get started with looking into how this plugin exactly works I would like to ask if the free version of this plugin will keep working in 1.17. We don't really have any budget to get paid plugins since we don't accept any donations or payments from our players, so if the free version of this plugin will no longer work in 1.17 then we would rather not spend time & effort to set this up only to remove it again once we update to 1.17.

**Comment by PyvesB** [comment]
Hello @KingOfMyGames ! 👋🏻 

I don't know what Minecraft 1.17 is going to change, and consequently I don't know what changes will be needed in Advanced Achievements. If you don't want to donate via the premium resource listing on spigot.org, you can check out the project and build the source code yourself. 😉

**Comment by KingOfMyGames** [comment]
Alright thanks for the advice!

**Comment by PyvesB** [comment]
Changes were required, see 36f817c893736a5ca825992d6bb41192426462a0.
