### ISSUE TITLE
Total completed achievements and number in advancementscompleted are not same

### ISSUE THREAD

**Issue by VaclavKlima** [PyvesB/advanced-achievements#1029]
Hi is there any way to synchronize how many achievements player completed and number of completed achievements in section "advancementscompleted" ..
Somehow players have incorect values .. when they write command / aach stats they see bigger number then in "advancementscompleted" section .. some players have really big difference (like hundret of achievemenents) .. it wouldnt be that big problem but they have rewards for completing achievements and its really annoying to giving them that achievements manually.

**Comment by PyvesB** [comment]
Hello @VaclavKlima ! 👋🏻 

I suggest reading through  #914, that should clarify things.
