### ISSUE TITLE
MythicMobs kills

### ISSUE THREAD

**Issue by arceusxs2** [PyvesB/advanced-achievements#1035]
:information_source: **Basic information**

* Advanced Achievements version:  7.0.7
* Minecraft version:  1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read:  YES
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:  Yes
* Spigot username:  1ntent1on

:question: **Help request**

Hello, im having a problem with setting up achievement about killing mythicmobs, i used the example with the skeleton knight but for some reason it doesnt work, netiher does the example one.

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @arceusxs2! 👋🏻 

Does #831 help?

**Comment by arceusxs2** [comment]
Hello, tried giving all of the permissions but it still doesnt work sadly. Also downloaded the thing for debugging and used all permissions from it but it also didnt help.

**Comment by PyvesB** [comment]
Okay. Could you please share the relevant configuration section of both Advanced Achievements and MythicMobs, as well as the logs that you saw printed with the debugging version?
