### ISSUE TITLE
Bungee Mode Issues

### ISSUE THREAD

**Issue by Viictiri** [PyvesB/advanced-achievements#1041]
:information_source: **Basic information**

* Advanced Achievements version: 7.0.4
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username: Viictiri

:question: **Help request**

I am having trouble with the bungee mode. I have it turned on, my database set as MySql, and the user and password set up. Even though I have all of that, I keep getting:

> [17:52:09 ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
> com.hm.achievement.exception.PluginLoadError: Failed to establish database connection. Please verify your settings in config.yml.

Attached is the full error and configuration I have.

:wrench: **Configuration**

> [17:50:02 ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
> com.hm.achievement.exception.PluginLoadError: Failed to establish database connection. Please verify your settings in config.yml.
>         at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:106) ~[?:?]
>         at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:145) ~[?:?]
>         at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:49) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-509]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-509]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-509]
>         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-509]
>         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-509]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Paper-509]
>         at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-509]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-509]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-509]
>         at java.lang.Thread.run(Thread.java:834) [?:?] 

````#======================================================================================================================#
#                                                  DATABASE SETTINGS                                                   #
#                                                                                                                      #
#                       The database is where all player statistics and achievements are stored.                       #
#======================================================================================================================#

# Make a daily backup of your local database (if sqlite or h2) when the server restarts.
DatabaseBackup: false

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: mysql

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix), the plugin does
# an automatic renaming. Otherwise you must rename tables manually. Do a full server restart for this to take effect.
TablePrefix: ""

# When using groups of subcategories for Multiple action achievements (e.g. snow|snow_block|ice), you must ensure that
# the value of this parameter is greater than the total number of characters in the group. Unless you use groups of very
# large sizes, you don't need to change this value.
TableMaxSizeOfGroupedSubcategories: 128

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &, for
# example "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ""

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: "jdbc:mysql://localhost:3306/achievements"
DatabaseUser: 
DatabasePassword:

**Comment by PyvesB** [comment]
Hello @Viictiri ! 👋🏻 

Careful, you've leaked your database password is in clear text, I suggest changing it.

I don't see anything obviously wrong in your configuration. Are you sure you've called your MySQL database `achievements`? Are you sure the username and password are right as well, in other words can you connect via the MySQL command line tool using these credentials?

**Comment by Viictiri** [comment]
I'm double checking everything and it looks like it's working fine. I'll try a different log in.

**Comment by PyvesB** [comment]
Any luck with the different login @Viictiri ? Worth noting that I'll be away for the next 4 weeks, I'll not be able to provide any further support.

**Comment by Viictiri** [comment]
Not yet, but I’m sure I can figure it out! Thank you for responding anyways and have a nice break!
