### ISSUE TITLE
Custom items?

### ISSUE THREAD

**Issue by Mystiia** [PyvesB/advanced-achievements#1042]
Hi, I bought advanced achievements for my server today and upon configuration of the achievements, I couldn't figure out how to add custom items to the reward for an achievement being completed. The code generally requires a command block to execute, so I'm just wondering if it'd actually be possible or not? There are two types of items I was wanting to add, one is a custom item using NBT tags and Optifine to give it a custom texture (a currency) and the other is just a regular Minecraft item, but with a custom name and lore. The code looks something like this when used in a command block for the regular item:

/minecraft:give @p paper{display:{Name:'[{"text":"Relic Voucher","italic":false,"color":"aqua","bold":true}]',Lore:['[{"text":"","italic":false}]','[{"text":"This is a voucher for a custom Relic.","italic":false,"color":"white"}]','[{"text":"The Relic ","italic":false,"color":"white"},{"text":"will","bold":true},{"text":" count towards Kingdom","bold":false}]','[{"text":"Relic counts.To claim, give this to","italic":false,"color":"white"}]','[{"text":"an Admin/Owner and submit a modmail on","italic":false,"color":"white"}]','[{"text":"Discord for further instructions.","italic":false,"color":"white"},{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"{aachr101}","italic":false,"color":"gold"}]']},Enchantments:[{}]} 1

I'm a relatively new dev, so excuse my ignorance here! Please let me know if this is possible.

Thank you!

**Comment by PyvesB** [comment]
Hello @Mystiia ! 👋🏻 

Please use the suggested issue templates in the future. 😉 

Does [this Wiki section](https://github.com/PyvesB/advanced-achievements/wiki/Rewards#custom-commands) help solve your issue?

**Comment by PyvesB** [comment]
Did the documentation help @Mystiia ? In particular did you try the `PLAYER` placeholder? Worth noting that I'll be away for the next 4 weeks, I'll not be able to provide any further support.
