### ISSUE TITLE
Better appearance and a few new features

### ISSUE THREAD

**Issue by GejmronCZ** [PyvesB/advanced-achievements#1045]
# **New features in config/gui**
* ### achievements_enchant: true/false
 If you get all the successes in the given category, then in the aach list the representative item is enchanted. This will help you navigate the unfinished categories.

* ### achievements_lore: true/false
If you want, you can add this to gui.yml. This option on/off your own lore on finished achievements or entire categories in /aach list.

* ### Subcategories
I know this idea is in other threads, but I have to mention it.
There is very big space for upgrade so you can change representative items like normal categories. If you want, you can change the representative items in the categories or subcategories after getting all the achievements. This will allow much more editing options.
The previous 2 points can also be applied to these subcategories like this ↓

* ### achievements_enchant_sub: true/false
* ### achievements_lore_sub: true/false

Only for author: gejmroncz@seznam.cz

**Comment by PyvesB** [comment]
Hello @GejmronCZ ! 👋🏻 

>  achievements_enchant: true/false
> achievements_enchant_sub: true/false

I believe that the enchantment information will appear when hovering over the items in the GUI, which will be confusing for users. This is a Minecraft limitation and I'm not aware of any ways to disable it.

> achievements_lore: true/false
> achievements_lore_sub: true/false

I do not understand the benefit of these options. Why would one want to disable lores for categories for which all achievements have been received?

**Comment by GejmronCZ** [comment]
Hello @PyvesB 
1. You can add any enchant you want like Unbreaking X in much plugins.
2. No, you misunderstood that. I meant it overall, not after getting it. If you want them there, leave them on, if not, turn them off. That is all.

**Comment by PyvesB** [comment]
>     2\. No, you misunderstood that. I meant it overall, not after getting it. If you want them there, leave them on, if not, turn them off. That is all.

If all lores are removed, you can no longer tell which achievement is which, can you? I don't see the point.

**Comment by GejmronCZ** [comment]
Dude, you should probably realize what the name is and what lore. I didn't say a word about the names, only about the additional lore as a reward / easter egg.

**Comment by PyvesB** [comment]
I'm not sensing this discussion as being very constructive. Next time you want to interact with an open-source community, I also recommend using a non-abusive profile picture.

**Comment by GejmronCZ** [comment]
This string is only my idea how to make this plugin better. It's not my problem that you don't know the concepts. BTW it's just a profile picture, nothing more. Everyone can have the profile they want. I like that [movie](https://www.csfd.cz/uzivatel/689707-gejmroncz/o-mne/). 

If you still have any questions, I'll be happy to answer them. :)
