### ISSUE TITLE
Max Health Changes

### ISSUE THREAD

**Issue by woodiestpack5** [PyvesB/advanced-achievements#1052]
:information_source: 

* Advanced Achievements version: 7.1.1
* Minecraft version: 1.17.1
* [Wiki] yes
* [Existing issues] yes
* Spigot username: WoodiestPack5

:question: How to change Max Health once earned.

I have certain achievements set to increase Max health by one point. I have been testing and it gives myself the max health. My question is once earned how can I remove it. If I have to remove/reset achievement progress and a player has earned the max health point how do we take it away. I have reset the achievement and deleted the progress however the heart stays. This is the same with Max Oxygen.

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @woodiestpack5 ! 👋🏻 

One option would be to do what another user shared in #416, another option would be to create a temporary achievement with a negative health reward value, give it to the user and then delete it again. 😉

**Comment by woodiestpack5** [comment]
Yes that worked. Also is there a way to disable achievement categories? I have man them invisible from the gui however players can still make progress towards the default advancements. When I delete them in the config.yml and reload the plugin it regenerates the default advancements back into the config.yml

**Comment by PyvesB** [comment]
> Also is there a way to disable achievement categories? I have man them invisible from the gui however players can still make progress towards the default advancements. When I delete them in the config.yml and reload the plugin it regenerates the default advancements back into the config.yml

This message will hopefully help: https://github.com/PyvesB/advanced-achievements/pull/979#pullrequestreview-611052956
