### ISSUE TITLE
Need a list of achievement catagories

### ISSUE THREAD

**Issue by Scyrizu** [PyvesB/advanced-achievements#1053]
:information_source: **Basic information**

* Advanced Achievements version:  7.1.1
* Minecraft version: 1.17.1. 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read:Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username:  Scyrizu
:question: **Help request**

I need a list of advanced achievements categories and formatting as they're not listed on the wiki and after formatting the config file to disable them in the GUI the plugin just generates errors and no longer functions
:wrench: **Configuration**

 Please paste relevant configuration sections in the code block below.. 
````
DisabledCategories:
#- AdvancementsCompleted
  - Breaks
  - Crafts
  - PlayerCommands
  - Arrows
  - Snowballs
  - Eggs
  - Treasure
  - ItemBreaks
  - EatenItems
  - Shear
  - Milk
  - LavaBuckets
  - Trades
  - Anvils
  - Enchantments
  - Beds
  - MaxLevel
  - Potions
  - PlayedTime
  - DistanceFoot
  - DistancePig
  - DistanceHorse
  - DistanceMinecart
  - DistanceBoat
  - DistanceGliding
  - DistanceLlama
  - ItemDrops
  - ItemPickups
  - HoePlowings
  - Fertilising
  - Taming
  - Breeding
  - Brewing
  - Fireworks
  - MusicDiscs
  - EnderPearls
  - PetMasterGive
  - PetMasterReceive
  - Smelting
  - TargetsShot
  - RaidsWon
  - Riptides
````

**Comment by PyvesB** [comment]
Hello @Scyrizu ! 👋🏻 

The default configuration files, including a list of all categories can be found in this folder:
https://github.com/PyvesB/advanced-achievements/tree/master/advanced-achievements-plugin/src/main/resources

**Comment by Scyrizu** [comment]
Thank you so much for all of your help :D

**Comment by PyvesB** [comment]
You're welcome!
