### ISSUE TITLE
Disabled achievements still being granted, and other achievements being granted early.

### ISSUE THREAD

**Issue by Scyrizu** [PyvesB/advanced-achievements#1054]
:information_source: **Basic information**

* Advanced Achievements version: 7.1.1
* Minecraft version 1.17 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Scyrizu

:beetle: **Description**

After commenting out achievements and modifying existing ones, achievements commented out still are granted and those changed are granted early. For example the walk 1000 blocks is still being granted despite being commented out, and the place four chests achievement is being granted after placing one chest.

:page_facing_up: **Server logs**

````

````

:wrench: **Configuration**

Please paste relevant configuration sections in the code block below.
````
# When a specific block is placed (available names: github.com/PyvesB/AdvancedAchievements/wiki/Material-names).
Places:  
  campfire:
    1:
      Goal: Place 1 campfire.
      Message: §6I will survive!
      Name: place_1_campfire
      DisplayName: Survivalist 3
  stone:
    5:
      # Optional, used in /aach list when achievement not yet received, and in advancements.
      Goal: Place 5 stone.
      # Description; displayed when receiving achievement, and in /aach book and /aach list.
      Message: §6You have placed 5 stone!
      # Database name, must also be used in /aach delete and /aach check.
      Name: place_5_stone
      # Displayed when receiving achievement, and in /aach book and /aach list.
      DisplayName: Laying a foundation
  chest:
    4:
      Goal: Place 4 chests.
      Message: §6You have placed 4 chests!
      Name: place_4_chest
      DisplayName: Building a home

DistanceFoot:
#  1000:
#    Goal: Travel 1000 Blocks with your feet.
#    Message: You traveled 1000 blocks by foot!
#    Name: distancefoot_1000
#    DisplayName: Big Walker 
````

**Comment by PyvesB** [comment]
Hey @Scyrizu ! 👋🏻 

Changing thresholds for existing achievements does not alter the underlying statistics: if the user had previously placed three chests, modifying one of the achievements does not change the fact that he has already placed three chests, so placing one extra chest will award the four chest achievement.

Regarding `DistanceFoot`, make sure that the category has not been duplicated in the config file, and make sure you've run _/aach reload_ after saving the file to refresh the plugin's configuration. 😉
