### ISSUE TITLE
Sequential achievements

### ISSUE THREAD

**Issue by Scyrizu** [PyvesB/advanced-achievements#1055]
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yese
* Spigot username:  Scyrizu

:clipboard: **Description**

An achievement for getting other achievements. E.X. Achievement: Survivalist Goal: Gain the Fishing, Water, and Stone achievements. Reward: Commands: Say: "Player is now a survivalist!"
-No -

**Comment by PyvesB** [comment]
Hey @Scyrizu ! 👋🏻 

See https://github.com/PyvesB/advanced-achievements/issues/82#issuecomment-667660727 for information on how to do this. 😉
