### ISSUE TITLE
Lang.yml

### ISSUE THREAD

**Issue by russianpeanut** [PyvesB/advanced-achievements#1057]
Hi i just have a question is there CZ land.yml for the latest version of the plugin?

**Comment by PyvesB** [comment]
Hello @russianpeanut ! 👋🏻 

There's one right here: https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-plugin/src/main/resources/lang-CZ.yml

It's a little outdated, but why not contribute back to the project and translate the missing texts? 😉

**Comment by PyvesB** [comment]
Feel free to submit a translation update at any point, I'll close this for now.
