### ISSUE TITLE
Does this plugin remove the vanilla JSON message?

### ISSUE THREAD

**Issue by Catches** [PyvesB/advanced-achievements#1064]
Can I edit the achievement message without removing the JSON message?
![image](https://user-images.githubusercontent.com/81335077/132007776-262f2e10-1517-4661-9e6f-2b740b384237.png)

**Comment by PyvesB** [comment]
Hello @Catches! 👋🏻 

Closing as the issue form was not used and this issue seems unrelated to Advanced Achievements anyway.

**Comment by Catches** [comment]
Hey @PyvesB,
I was just wondering if you could customize the achievement message in the plugin with the vanilla JSON support?

**Comment by PyvesB** [comment]
Advanced Achievements doesn't deal with Vanilla advancements. 😉

**Comment by PyvesB** [comment]
Advanced Achievements doesn't deal with Vanilla achievements. 😉
