### ISSUE TITLE
lang line problem

### ISSUE THREAD

**Issue by EdgarGDE** [PyvesB/advanced-achievements#1065]
### 🎆 Advanced Achievements version

7.2.0

### 🖥 Server version

Tuinity 1.16.5 Latest stable version

### 🚰 Spigot username

DarthEdard

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### ❓ Description

I can't set the following line inside config.yml:

Currently my line is like this: "achievement-new: '§aLogro Desbloqueado:'" (Ignore "")
But I want to do it like this, in some way possible! "achievement-new: '§e§kw §a>> Logro Desbloqueado: §6%aach_new_achievement% §a<< §e§kw'"

Is possible?

The problem is that AACH detects the end of the text inside the quotes as the achievement unlocked, which means that I cannot select a full format because it will be interrupted, I will show examples, if I manage to upload images it will be better.

### ⚙ Configuration

```
achievement-new: '§aLogro Desbloqueado:'
```

**Comment by PyvesB** [comment]
Hello @EdgarGDE ! :wave:

>  I will show examples, if I manage to upload images it will be better.

Yes, images would be great! You can simply drag and drop them in GitHub. 😉

**Comment by PyvesB** [comment]
I've implemented something that I believe corresponds to what you want, closing.

**Comment by EdgarGDE** [comment]
> I've implemented something that I believe corresponds to what you want, closing.

Sorry! I didn't answer because I completely forgot! I had emergency exits and my time is gone

**Comment by EdgarGDE** [comment]
Let me look for the option and show you what I'm talking about, basically AACH does not allow to change the message that appears when you unlock an achievement (in chat)

**Comment by EdgarGDE** [comment]
Because there is no placeholder to identify the new achievement, AACH uses the end of that line as a "placeholder" and the achievement appears there.

**Comment by EdgarGDE** [comment]
File: lang.yml
achievement-new: '§aNew Unlocked AACH:' #Here is the problem.
When the achievement appears in-game, it looks like this:
§aNew Unlocked AACH: Here is the AACH!
If I wanted the game to show it like this:
&e&k123 §aNew Unlocked AACH: &6Here is the AACH! &e&k123
It would change the line like this:
achievement-new: '&e&k123 §aNew Unlocked AACH: &6%new-placeholder-needed% &e&k123'
But no placeholder exist :( Is needed

**Comment by PyvesB** [comment]
I believe that's what I implemented, all is good :)

**Comment by EdgarGDE** [comment]
Because the original line detects that the end of the line is where the achievement will appear. achievement-new: '§aNew Unlocked AACH: #(here appear the aach)' #Here is the problem.

**Comment by EdgarGDE** [comment]
Wow, really? what is the new placeholder or the new setting?

**Comment by PyvesB** [comment]
Both `achievement-new` and `achievement-received` in _lang.yml_ will now support an `ACH` placeholder, similarly to a few other messages in that file. 😉

**Comment by EdgarGDE** [comment]
I add them with %%? Example: %achievement-new%

**Comment by PyvesB** [comment]
Well no, you'll simply need to use the `ACH` placeholder: `achievement-new: '§e§kw §a>> Logro Desbloqueado: §6ACH §a<< §e§kw'`

**Comment by EdgarGDE** [comment]
Really if it is what you wanted! but it does not work! watch this :(

**Comment by EdgarGDE** [comment]
https://imgur.com/KAbTY2x (Not working)
https://imgur.com/EcKJECK (Working, But is another plugin of "Souls" xd)
My line: achievement-new: ' §e§kw§a>>  Logro Desbloqueado: §6ACH  §a<<§e§kw'

**Comment by PyvesB** [comment]
Are you sure you've correctly recompiled the plugin from source?

**Comment by EdgarGDE** [comment]
What does it mean? I bought the plugin a few months ago and I am using the most current version.
Do you need me to show you my logs or any special data?

**Comment by PyvesB** [comment]
As you'll have noted, this feature was implemented three hours ago. If you're trying to use it in the current Spigot version which was released several days ago, it will not work. If you were familiar with Maven and Git, you could build the project's source code yourself, but it's probably simpler to just wait for the next release.

**Comment by EdgarGDE** [comment]
Oh I understand! I don't know how to do that because I'm not a developer :(

**Comment by EdgarGDE** [comment]
Sorry to bother you, but that role will be official, right?

**Comment by PyvesB** [comment]
> Sorry to bother you, but that role will be official, right?

What do you mean by "that role"?

**Comment by EdgarGDE** [comment]
Hi there! Now it works, I tried the update and it is great!

**Comment by EdgarGDE** [comment]
Sorry, if you don't understand me in some words, I don't speak English and I use a translator! but thanks!!! :D <3

**Comment by PyvesB** [comment]
It's okay! Glad you're enjoying the update!
