### ISSUE TITLE
AACH Commands placeholder not listed or missing

### ISSUE THREAD

**Issue by TheCashFire** [PyvesB/advanced-achievements#1066]
### 🎆 Advanced Achievements version

7.2.0

### 🖥 Server version

1.17.1 Paper

### 🚰 Spigot username

CashFire

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

With the new placeholders, they all work great except for one; the Commands section (not to be confused for the PlayerCommands section). The wiki does not list a placeholder for this section, and nothing I have tried will show the correct value. I might just have missed it, but I've spent half an hour now looking to no avail.

Is it just missing? Or am I crazy?

I assume it would be %aach_commands% and %aach_total_commands%, but none are listed. the /aach list GUI does read out correct numbers though, so I assume the placeholder is there, but either unlisted or inaccessable.

### 📄 Server logs

```

```

### ⚙ Configuration

```

```

**Comment by PyvesB** [comment]
Hello @TheCashFire ! 👋🏻 

The placeholders for the `Commands` category were simply never implemented. Will fix that in next update 😉

**Comment by TheCashFire** [comment]
Appreciate it! Had me scratching my head all afternoon.

**Comment by PyvesB** [comment]
Looking into this in more details, `%aach_commands%` would not make sense as a placeholder. All other category placeholders correspond to the statistics for that category/sub-category. As the `Commands` category only contains achievements that can be given via a command, there is no statistic for that category. Only `%aach_total_commands%` makes sense, as that simply corresponds to the number of achievements in that category.

**Comment by TheCashFire** [comment]
On that, I would agree. I just need a placeholder to count the number of achievements in that category for custom GUI purposes. %aach_total_commands% is required. :)

**Comment by PyvesB** [comment]
There you go, `%aach_total_commands%` was implemented.

Would you like to update the PlaceholderAPI documentation? You can do it from the web UI by simply pressing edit on the following file: https://github.com/PlaceholderAPI/PlaceholderAPI/blob/docs/wiki/wiki/Placeholders.md#advanced-achievements

You'll then be become one of the contributors to the PlaceholderAPI repository! :)

**Comment by TheCashFire** [comment]
Awesome! I've gone ahead and proposed %aach_total_commands% to the total achievements section. Thanks for the opportunity!

**Comment by PyvesB** [comment]
> I've gone ahead and proposed %aach_total_commands% to the total achievements section.

Have you? I can't see the pull request on the Placeholder API repo ^^

**Comment by PyvesB** [comment]
So far, you've only made the commit, you need to go to the following URL and actually create the pull request:
https://github.com/PlaceholderAPI/PlaceholderAPI/compare/docs/wiki...TheCashFire:patch-1

**Comment by TheCashFire** [comment]
I made a pull request, it just didn't work before as I wasn't logged in.
I'm not sure if it went to the right person, so let me know if I did it
correctly!
