### ISSUE TITLE
Dropping items if inv is full

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/advanced-achievements#1068]
### 🎆 Advanced Achievements version

7.2.0

### 🖥 Server version

1.17.1

### 🚰 Spigot username

JHarris12345

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

Can item rewards be dropped on the floor if their inv is full? Or some way to tell if their inv was full upon winning? Right now items are just lost

### 📄 Server logs

```

```

### ⚙ Configuration

```

https://pastebin.com/gWjF4Gb6
```

**Comment by PyvesB** [comment]
Hello @JHarris12345 ! 👋🏻 

You claim to have searched duplicate issues, yet I'm unsure how you managed to miss an issue that you created yourself,  #982. I had requested some precise additional pieces of information at the time. You didn't provide them despite my multiple attempts to follow up, and again haven't shared the required information today. You seem to have a record of opening issues and then never responding (examples: #982, #895, #857, #654, etc.). Am I wasting my time?

**Comment by PyvesB** [comment]
Additional information was (finally) provided in #720, the problem should now be fixed. :)
