### ISSUE TITLE
empty achiements

### ISSUE THREAD

**Issue by globemaster123** [PyvesB/advanced-achievements#1069]
### 🎆 Advanced Achievements version

7.2.0

### 🖥 Server version

1.17.1

### 🚰 Spigot username

globemaster123

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### ❓ Description

Why can't I just delete some/every achievement in the config.yml?
My goal is, to create just a few achievements so I can play customised challenges with my friends, but everytime I try to delete some achievements and reload the plugin, they'll just getting added in the config again.

### ⚙ Configuration

```

```

**Comment by PyvesB** [comment]
Hello @globemaster123 ! 👋🏻 

See https://github.com/PyvesB/advanced-achievements/pull/979#pullrequestreview-611052956, it will hopefully shed some light on your problem.
