### ISSUE TITLE
 Error occurred while enabling AdvancedAchievements v7.2.0 (Is it up to date?)

### ISSUE THREAD

**Issue by Hyronymos1337** [PyvesB/advanced-achievements#1070]
### 🎆 Advanced Achievements version

7.2.0

### 🖥 Server version

1.8.8

### 🚰 Spigot username

Twerion

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

error on startup

### 📄 Server logs

https://pastebin.com/JmjAAUva

### ⚙ Configuration

```

```

**Comment by PyvesB** [comment]
Hello @Hyronymos1337 ! 👋🏻 

It looks like I accidentally broke compatibility with Minecraft versions 1.7 & 1.8 in the latest update. Thanks for reporting this, I'll work on a fix. In the meantime, please stick with version 7.1.1 of Advanced Achievements. 😉

**Comment by Hyronymos1337** [comment]
thank you
