### ISSUE TITLE
AACH disables itself with TNE 0.1.1.13

### ISSUE THREAD

**Issue by MetaverseRPN** [PyvesB/advanced-achievements#1077]
### 🎆 Advanced Achievements version

7.2.3

### 🖥 Server version

1.17.1

### 🚰 Spigot username

NuclearNIX

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

When using both AACH and TNE 0.1.1.13 AACH disables itself giving this error: Cannot invoke "net.tnemc.core.common.EconomyManager.currencyManager()" because the return value of "net.tnemc.core.TNE.manager()" is null

### 📄 Server logs

```
https://gist.github.com/nacjm/350970f757c34d2b76325e4447d725cc
```

### ⚙ Configuration

```

```

**Comment by PyvesB** [comment]
Hello @nacjm ! 👋🏻 

This is a known problem with The New Economy, see https://github.com/TheNewEconomy/TNE-Bukkit/issues/458 for more details. Feel free to follow up with the author on that issue. 😉
