### ISSUE TITLE
Player data reset

### ISSUE THREAD

**Issue by carreb** [PyvesB/advanced-achievements#1086]
### 🎆 Advanced Achievements version

6.2.1

### 🖥 Server version

1.17.1

### 🚰 Spigot username

carrreb

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### ❓ Description

Upon updating to 1.17.1, all of my achievements data was reset. I am using the H2 Database and can supply files from before and after updating if needed. The plugin functions fine, but all existing player data was reset.
I've tried uploading the backed up versions but they are not being read properly or being erased when uploaded.
I've tried figuring out how to open the database to see all the player data and set it back to normal manually but I can't seem to find where that is stored.

If you need to see some of the files, please let me know the names of them and I will send them asap.
![image](https://user-images.githubusercontent.com/32069843/138563352-eee2ff92-b64d-4bc9-bd0f-6216236f4531.png)

### ⚙ Configuration

```
# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: true

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: h2

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ''

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ''

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: jdbc:mysql://localhost:3306/minecraft
DatabaseUser: root
DatabasePassword: root
```

**Comment by PyvesB** [comment]
As the project is being sunset, I'll go ahead and close this (see #1083 or spigotmc.org for more information). The repository will be archived soon. Hopefully the tips I've provided here will have helped you solve the issue. 😉
