### ISSUE TITLE
Only OP player can get ahiev

### ISSUE THREAD

**Issue by Bronzwar** [PyvesB/advanced-achievements#1089]
### 🎆 Advanced Achievements version

8.0.1

### 🖥 Server version

1.17.1.

### 🚰 Spigot username

Bronzwar

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### ❓ Description

Why only OP played can get Achievements ?

### ⚙ Configuration

```
https://paste.helpch.at/opamoxozix.shell
```

**Comment by PyvesB** [comment]
As the project is being sunset, I'll go ahead and close this (see #1083 or spigotmc.org for more information). The repository will be archived soon. Hopefully the link I've provided here will have helped you solve the issue. 😉
