### ISSUE TITLE
Option to exclude command based achievements from AllAchievementsReceivedRewards.

### ISSUE THREAD

**Issue by mibby** [PyvesB/advanced-achievements#340]
I have a list of command based achievements that are used to reward players for event participation and various placements. I also have a reward given to players who get all achievements unlocked with AllAchievementsReceivedRewards.

```
AllAchievementsReceivedRewards:
  Command:
    Execute: lp user PLAYER permission set deluxetags.tag.Overachiever
```

Would it be possible to have an option to exclude command based achievements from being needed in the AllAchievements reward? Since command based achievements may not be achievable by most people in my case and are used reluctantly for special occasions and single-time unlocks.

**Comment by PyvesB** [comment]
Hello @mibby !

This seems like a reasonable request. I've been quite busy lately, but maybe someone else will pick it up in the meantime. 😉 

Cheers,

Pyves

**Comment by supertassu** [comment]
I'll take a look on this soon.

**Comment by supertassu** [comment]
Oh wait: @PyvesB has done this just comparing total amount of achievements and amount of achievements the player has received.

https://github.com/PyvesB/AdvancedAchievements/blob/master/src/main/java/com/hm/achievement/listener/PlayerAdvancedAchievementListener.java#L182-L184

Pyves, what's the easiest way to get advancement's category by it's name?

Tassu

**Comment by PyvesB** [comment]
No news for quite a while and I don't see any huge value in this feature, especially as no one else has asked for it. I'll go ahead and close this issue. 😉
