### ISSUE TITLE
Idea: Support scoreboard objectives

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/advanced-achievements#38]
Hello,

if it's possible to support scoreboard objectives you could make A LOT of custom achievements, also with own plugins that use the scoreboard. Just a suggestion for future updates. :)

**Comment by PyvesB** [comment]
Hello,

I'm slightly confused, what exactly do you mean by "support scoreboard objectives"?

**Comment by Platinteufel** [comment]
http://minecraft.gamepedia.com/Scoreboard#Objectives_commands
Let's say I've coded my own minigame and increase a scoreboard score for the winner of this game. If there would be support for scoreboard objectives I could make a achievement "Win 10 times MyMinigame" if the player reaches a value of 10 for this specific scoreboard.

**Comment by PyvesB** [comment]
I've never really used these before, I would have to look into them. :-)

**Comment by Sketaful** [comment]
Couldn't you just make a custom command achievement and then put that as a price after 10 wins?

**Comment by PyvesB** [comment]
It's been over four years, no one else has ever asked for this. Given that there's a simple enough alternative suggested above, I'll go ahead and close this. :)
