### ISSUE TITLE
GUI Open Command for Categories.

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/advanced-achievements#694]
A open command for a single categorie.

Like: /aach open blockplace or /aach open kills

That feature would make it possible, to create a own GUI for the Achievement list.

**Comment by PyvesB** [comment]
Hello, unsure why you would want to create your own GUI given that the current one is extensively customisable, but if someone has a precise use case and wants to contribute, I'm happy to review a pull request. I would suggest sticking to the _/aach list_ command and using properly capitalised category names, for example _/aach list Places_. 😉

**Comment by R4zzerYT** [comment]
Can you please add that? I want to build a menu with a better Overview for achievements, but I need that feature for it.

**Comment by n54b** [comment]
No one is motivated to do this? It doesn't take long to do theoretically, one command to open each "menu" should be enough :)
I suck at java or I'd have done it myself ^^

**Comment by n54b** [comment]
@PyvesB with the premium pass could you take care of this ticket? If yes, I buy the plugin immediately :p

**Comment by PyvesB** [comment]
I still don't see a real use case for this, and therefore I'm not convinced it would be useful to many users. Could you describe why this feature is important to you?

**Comment by n54b** [comment]
Being able to open each category with a specific command allows those who want to open the menu or create menus (see deluxemenus), because the current menu is not very practical ... All is put in bulk ...
That's why I thought that adding the possibility to open each category with a command was more convenient for you than giving the possibility to modify the menus completely.

**Comment by PyvesB** [comment]
Done, _/aach list Places_ and isilar is now possible. Was slightly harder than I had anticipated, but not the end of the world either. I chose not to include this feature in the _/aach list_ auto-completion, as it's intended for other integrations rather that direct player usage.

**Comment by n54b** [comment]
Hello, thank you very much and promised thing due! I just bought the plugin to support you :)

**Comment by PyvesB** [comment]
> 
> 
> Hello, thank you very much and promised thing due! I just bought the plugin to support you :)

You're welcome, thanks for purchasing! If you do something fun with your custom GUI, feel free to share a screenshot or two. :wink:
