### ISSUE TITLE
custom skulls in place event

### ISSUE THREAD

**Issue by vladimirgal1012** [PyvesB/advanced-achievements#708]
Hello everyone,

I would like to just kindly ask if its possible to listen for a custom skull place event. e.g.:

```
player_head{display:{Name:"{\"text\":\"Monster (StarTubers)\"}"},SkullOwner:{Id:"d5f4edae-7968-490e-bad7-18a9bdc13d75",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTM3YzUxYTY1MjQ2ZDUwMjBhYjQ1NGFiMjg3MjAyZGYwMDlkNWVhZDVhZWRmZmViZmRlYTljOTUwZjc0ZmFmOCJ9fX0="}]}}}:
    1:
      Goal: Place a skull.
      Message: You are killin it!
      Name: place_1_playerhead
      DisplayName: Skull placer
```

I know it looks silly but I would really like to use something like this.

Thank you all :)

**Comment by PyvesB** [comment]
Hello @vladimirgal1012! Thanks for the suggestion. Are these heads provided by a third-party plugin or are they part of Vanilla Spigot/Bukkit?

**Comment by vladimirgal1012** [comment]
I am using 3rd-party plugin for getting heads called "HeadDatabase". Don't know if it will be easier to hook in on it or not but I would really love to see this feature. Thanks for you response 💯

**Comment by PyvesB** [comment]
If it's a custom plugin, it may be tricky. We need to check whether some bit of generic metadata can be easily retrieved by Advanced Achievements when handling place events for these skulls - this would allow the same bit of code to work for other custom plugins!

**Comment by vladimirgal1012** [comment]
I can do some research about skulls and maybe after that you could add mapper when property will be skull so users can specify skullOwner etc as a property maybe ? I'll hit you with a detailed message about custom skulls

**Comment by vladimirgal1012** [comment]
**Player heads:**
A player head is a skull, linked to the current texture of a certain player in minecraft. You can use those heads in any Minecraft version. Since the skull is linked to a player, it will change the texture if the player change his texture. If the player change his username, a newly created player head with his name will have no texture.

**Custom heads:**
A custom head is a skull, linked to a texture stored on the servers of Mojang. In contrast to player heads, custom heads don't use playernames. Since the commands you use to get those heads neads NBT-Tags from Minecraft 1.8, you can't use them in earlier versions of the game. Since the skull is directly linked to files on the Mojang servers, the texture will never change.

To create a custom skull, upload the skin to your minecraft account and generate a Give-Code using the custom heads generator. Afterwards, you can change back the skin of your minecraft account - the Give-Code will still work.

**Comment by vladimirgal1012** [comment]
Taken from https://minecraft-heads.com/faq with more detailed info

**Comment by vladimirgal1012** [comment]
Example command to get a skull in vanilla way:
`/give @p minecraft:player_head{display:{Name:"{\"text\":\"Quartz Bricks\"}"},SkullOwner:{Id:"e992495b-b646-43ae-81e1-d99724d65329",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTFiNGIyNjhlOGVhMTZhMjQwMWYyZThiOTg0Mjg4NzdkZTViZTI5Y2QzMjkxNzIzMjVmNTA3NzEzMGM0YzljOSJ9fX0="}]}}} 1`

**Comment by PyvesB** [comment]
Thanks for the info. I'm not sure whether NBT tags can be accessed though the Bukkit API, I've got a feeling it requires NMS (`net.minecraft.server` classes, not part of the public API). Would have to plug in a debugger and double check what is directly accessible through `BlockPlaceEvents`.

**Comment by PyvesB** [comment]
Ugh, I wanted to test things out but noticed that HeadsDatabase was a premium resource...

**Comment by vladimirgal1012** [comment]
There might be some free resources as well. HeadsDatabase doesnt have any api you could try to use ?

**Comment by PyvesB** [comment]
Maybe [Player Heads](https://dev.bukkit.org/projects/player-heads)? We used it years and years ago on the server that I led...

**Comment by vladimirgal1012** [comment]
Yea that could work too. 👍

**Comment by PyvesB** [comment]
This will be available in the next plugin release: you'll be able to use any custom display name for the `Places` category. Tested with Player Heads and Custom Heads. 😉
