### ISSUE TITLE
Get all achivements from category

### ISSUE THREAD

**Issue by Darkool** [PyvesB/advanced-achievements#762]
Hello there,

Any chance to retrieve all achivements object from a category type or category name using your API? 

I would like to get all "custom" achivements for example and check if player have it or not, or even his progress.

Thanks.

Best regards.

**Comment by PyvesB** [comment]
Hello @Darkool,

The API currently allows you to get a player's progress for a given category using the following method:
https://github.com/PyvesB/AdvancedAchievements/blob/42fd2e449b1954da5327ac95262db3ab250f53c2/advanced-achievements-api/src/main/java/com/hm/achievement/api/AdvancedAchievementsAPI.java#L110

There is however no way to currently list all achievements belonging to that category.

Out of interest, what is your use-case? 😉

**Comment by Darkool** [comment]
Hi @PyvesB ,

I would like to create my own achivement GUI,

So I need actually reply your menu for custom category, modifiying lore, slots, and adding more placeholders.

any plan to implement that on your api?

Best regards.

**Comment by PyvesB** [comment]
To be honest, I'll probably not have much bandwidth to expand the API in the coming weeks, however, contributions are welcome!

**Comment by n54b** [comment]
would someone have had time to look into it? :D I'm trying to do the same thing :)

**Comment by PyvesB** [comment]
I think that once  #789 is landed, it will be easier to add an API for this. :)

**Comment by PyvesB** [comment]
The API now features a method called `getAllAchievements()`. You can simply get all achievements for a given category like this:
```
advancedAchievementsAPI.getAllAchievements()
    .stream()
    .filter(a -> a.getCategory() == NormalAchievements.LAVABUCKETS)
    . ...
```
