### ISSUE TITLE
[Bug] AdvancementCompleted without having enough achievements

### ISSUE THREAD

**Issue by hitakiller** [PyvesB/advanced-achievements#764]
:information_source: **Basic information**

* Advanced Achievements version:  6.1.2
* Minecraft version: 1.15.2 (Papermc latest)
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

Players on my server receive " AdvancementsCompleted " without having requested number of achievements. Console didn't display any error related to AdvancedAchievements and when verifying their succes number, we see that they don't met prerequisites.

:wrench: **Configuration**

There is our config of AdvancementsCompleted. We use MySQL storage wich is functionnal 'cause all others success are ok.

````
# Quand un certain de nombre de succès sont terminés.
AdvancementsCompleted:
  25:
    Goal: Compléter 25 succès.
    Message: §725 succès complétés !
    Name: advancements_25
    DisplayName: §3Petit joueur
    Reward:
      Money: 150
  50:
    Goal: Compléter 50 succès
    Message: §750 succès complétés!
    Name: advancements_50
    DisplayName: §3Quelques succès
    Reward:
      Command: xp add PLAYER 25 levels
  100:
    Goal: Compléter 100 succès
    Message: §7100 succès complétés!
    Name: advancements_100
    DisplayName: §3Belle collection
    Reward:
      Item: diamond_helmet 1
  149:
    Goal: Compléter tous les succès
    Message: §7Tu as complété tous les succès !
    Name: advancements_149
    DisplayName: §3Joueur de l'extrême
    Reward:
      Item: paper 1 §1B§2o§3n §4p§5o§6u§7r §82 §9b§1o§2u§3q§4u§5i§6n§7s r§8a§9c§1c§2o§3m§4m§5o§6d§7a§8g§9e
        §1!§6(succès aach)
````

Maybe we did a mistake in config, can you help us ? If you need more informations we can provide it to you !
Thank's in advance for your support !

Sorry for english mistakes i'm french.

**Comment by PyvesB** [comment]
Hello @hitakiller, thanks for sharing the issue. @CrabMustard could you please help with investigating this one? 😉

**Comment by PyvesB** [comment]
Any news on this issue?

**Comment by hitakiller** [comment]
I've searched where's problem but i've found nothing, i'm waiting for support and have disabled AdvancementCompleted for the while.

This bug is still here in last version (6.1.3).

Have you an idea, i've done something wrong ?

**Comment by PyvesB** [comment]
There may be a misunderstanding here. The `AdvancementsCompleted` category counts the number of vanilla Minecraft advancements, not Advanced Achievements' achievements!

**Comment by hitakiller** [comment]
Oh Ok ! Is there a category wich count Customs Advancements ?

**Comment by PyvesB** [comment]
> Oh Ok ! Is there a category wich count Customs Advancements ?

If you mean _achievements_, no there is no category that currently counts them. However, there is a `AllAchievementsReceivedRewards` that rewards players when you've received all achievements, as well as a feature request to further extend this, #340. 😉
