### ISSUE TITLE
Achievements reset!

### ISSUE THREAD

**Issue by Imerlithh** [PyvesB/advanced-achievements#802]
:information_source: **Basic information**

* Advanced Achievements version:  6.1.3
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes.
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes.

:beetle: **Description**

We don't have a SQL server for our server since its a small server. The problem is we're playing with "whitelist: on" for obvious reasons. Since we have "online mode=false", whenever we need to add someone to the server we need to turn whitelist off, invite the new player, then turning it on and then adding the player to the whitelist. The problem is whenever we turn on/off whitelist and restart the server, players achievements will reset. I'm using lastest paper server api, no plugin conflicts. Is the problem is clientside or does it have to do with plugin itself?

:page_facing_up: **Server logs**

:wrench: **Configuration**

**Comment by PyvesB** [comment]
Hello @Imerlithh,

Advanced Achievements uses the UUID (unique identifiers) of players to store all information, regardless of the database type.

When "online mode=true", the UUIDs never change as they're tied to a player's official Minecraft account. With "online mode=false", they are different, but generally don't change for a given server. I'm guessing that when you turn the whitelist on/off and then restart the server, this somehow breaks that state and causes all player UUIDs to be changed.

Unfortunately, there's nothing much I can do in Advanced Achievements about this. I don't know what plugins/software you're using for the whitelisting, but probably something worth flagging up with them. :wink:
