### ISSUE TITLE
Add API functionality to increase achievements

### ISSUE THREAD

**Issue by deeprobin** [PyvesB/advanced-achievements#807]
:clipboard: **Description**
Currently I am increasing the number over SQL, but the problem is that this is only updated on the next join. 
Therefore you could add an API method to increase this manually.

```kotlin
fun insertOrUpdateVotes(target: UUID) {
        this.dataSource.connection.use {
            val statement =
                it.prepareStatement("INSERT INTO aac_custom (`playername`, `customname`, `custom`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `custom` = `custom` + 1;")
            statement.setString(1, target.toString())
            statement.setString(2, "votes")
            statement.setInt(3, 1)
            statement.execute()
        }
    }
```

**Comment by PyvesB** [comment]
Hello @deeprobin,

Thanks for the feedback, would you like to submit a pull request to extend the API? :)

**Comment by deeprobin** [comment]
If I can spare some time over the next few days, maybe I can take a closer look at the project and make a pull request.

Nice that you are so committed to your project.
