### ISSUE TITLE
Use kebab-case instead of CamelCase

### ISSUE THREAD

**Issue by deeprobin** [PyvesB/advanced-achievements#808]
:clipboard: **Description**

Usually you name Git repositories with kebab-case. I would suggest renaming this repository to advanced-achievements. The GitHub repository name doesn't have to match the project name. By naming the project in kebab-case, a repository looks much more professional. 
If you want to overdo it, you can change your username, but that's not as important as the actual repository name.

**Comment by PyvesB** [comment]
Hello @deeprobin,

I do tend to use kebab case for my repositories nowadays, but when I named this one over half a decade ago, a vast majority of Minecraft projects had the repositories in camel case, including Bukkit itself and major plugins such as WorldEdit and the likes. I'm not sure how things have evolved in recent months and years, but I'm guessing there's some tension between what is most common in the wider industry and what is most common in a smaller community.

Ultimately I'm not too fussed. I can change it if you feel strongly about it. 😉

**Comment by deeprobin** [comment]
Hey @PyvesB,
thank you for your feedback.
Of course it's your decision, but I personally prefer kebab-case as it is the standard. 
I can't force you to do anything, but I would of course appreciate it if the project name could be changed to 'advanced-achievements' for example.

**Comment by PyvesB** [comment]
Done! :)
