### ISSUE TITLE
Mysql Issue

### ISSUE THREAD

**Issue by Tomigames** [PyvesB/advanced-achievements#820]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.0
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: no

:question: **Help request**
I am having issues connecting to mysql
https://paste.md-5.net/iwuwopequh.sql

:wrench: **Configuration**
https://paste.md-5.net/ayinuyuluz.makefile

**Comment by PyvesB** [comment]
Hello @Tomigames,

The exception is indicating "access denied for user", so I'm guessing either the username or the password you've specified in the configuration is incorrect. 😉

**Comment by Tomigames** [comment]
Never got it to work IDK its okey I am using the default one.
