### ISSUE TITLE
Customization of prefix / shamrock icon

### ISSUE THREAD

**Issue by mesl** [PyvesB/advanced-achievements#821]
Hello!
I've recently installed your plugin and am very happy to use it, Everything works expected though there is one little customization feature I'd like to have

I'd love to change the shamrock icon to just a prefix chat, For example &7[&fAchievements&7]&f

Is there a current way to do it I've missed? or is this a feature you would like to implement?

Hope to hear back from you
Kind regards
Merlyn

**Comment by PyvesB** [comment]
Hello @mesl,

I believe this is already possible: the `Icon` parameter doesn't actually need to be a single character, you should be able to put any random text with colours inside. 😉

**Comment by mesl** [comment]
Sorry! I thought i already thanked and closed you, Apparently I didn't so here it is:
Thank you very much for your quick reply and it indeed helped!
Kind regards
Merlyn
