### ISSUE TITLE
Add a first login placeholder (or when[date] the player achieve something)

### ISSUE THREAD

**Issue by jusobreira** [PyvesB/advanced-achievements#829]
Could you add a placeholder that tells when a player got an achievement? 

What I really want is a placeholder that tells me when the player first join the server, but if you add something like this exemple below, it could be usefull to.

- %aach_achieve_[what achievement you need to know when it was achieved]% - example: %aach_achieve_connections_1% 

And it give this info:

![image](https://user-images.githubusercontent.com/10175304/91049056-fbf1de00-e5f2-11ea-9ef8-c5e7d6f8da8a.png)

**Comment by PyvesB** [comment]
Hello @jusobreira,

Thanks for the suggestion, I believe this is being added by #789. 😉

**Comment by jusobreira** [comment]
Is this the proper usage? It's not working for me, i guess i'm doing something wrong

![image](https://user-images.githubusercontent.com/10175304/91658102-af981980-ea9c-11ea-9e99-c6efa62313a8.png)

**Comment by PyvesB** [comment]
Did you correctly check out the branch corresponding to that pull request and recompile the plugin from source?

**Comment by jusobreira** [comment]
I suposed that it was on the Spigot Version, I don't know how to recompile a plugin from the source. Thanks, i'll close the issue and wait for this feature on the Spigot version

**Comment by PyvesB** [comment]
Sorry if that wasn't clear. Do bear in mind that I'm not able to provide any timeline, as I'm not the person implementing the change. 😉
