### ISSUE TITLE
PlayedTime placeholder not working with deluxemenu

### ISSUE THREAD

**Issue by Bleache7500** [PyvesB/advanced-achievements#830]
* Advanced Achievements version: 6.2.0
* Minecraft version: 1.16.2
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes

Hi, i'm using deluxemenu on my server to make gui, and i want to make a new gui for the achievement. Everything is working fine but not the placeholder for the playedtime. When i use /papi parse me %aach_playedtime% it show me my playedtime but it seems that deluxemenu know how to interpret it. I saw in a issue that you change it to make it show youyour playedtime  in hours and not in seconds. I tried the version without that change and it worked so i think that change broke it with deluxemenu. Can you maybe undo that change or make it work again. 

There is my config that i during my investigation 

deluxemenu config in 1.16.2 : https://pastebin.com/Zf4Q4KST
screen of the in game gui : https://pics.narfaly.net/ARogxi9DlkHaNjX2LqW5ABPdw4QgxQId.PNG

deluxemenu confing in 1.12.2 : https://pastebin.com/2fG1Dt5n
screen of the in game gui : https://pics.narfaly.net/WsFCX91p4AnW8DA93PGTiGsef8SgEyx2.PNG

**Comment by PyvesB** [comment]
Hello @Bleache7500,

Unfortunately, I cannot view the screenshots you linked, I'm getting "Access denied" errors.

**Comment by PyvesB** [comment]
Any chance you could get the screenshots to work @Bleache7500 ?

**Comment by PyvesB** [comment]
Feel free to reopen when you get time to look into this again!
