### ISSUE TITLE
This idea, maybe?

### ISSUE THREAD

**Issue by msmanui** [PyvesB/advanced-achievements#837]
Look, i was aggresive and disrespectful, i admit that and i appoligze for that.

The plugin it self is great but the only thing im asking is to add more customazation of the gui. That means, to being able to change the display message or lore, or display items, or use another order for showing each achivement.
Here is an example of how it could be implemented, this of the plugin xlTournaments.

![image](https://user-images.githubusercontent.com/63617395/91916405-707fe900-ec93-11ea-81e7-46a44a2cb438.png)

So as u can see in the picture, in the lore u would only add the information u want, and the plugin wont crash if u dont include some info as its a free-lore-usage with placeholders to include the information u want.

**I will definitely donate at least 30 usd once the gui-customazation improved.**
I do have a big network (+200 players) specialzed in survivals, so i really want this plugin.

**Comment by PyvesB** [comment]
Start by repairing the damage you've done, showing support to the project and writing well-formed feature requests, rather than copy-pasting unintelligible messages around.

**Comment by msmanui** [comment]
> Start by repairing the damage you've done, showing support to the project and writing well-formed feature requests, rather than duplicating unintelligible messages across several issues.

The images it self, basically, explains why your plugin does not have full customazation in the gui.

**Comment by msmanui** [comment]
> Start by repairing the damage you've done, showing support to the project and writing well-formed feature requests, rather than duplicating unintelligible messages across several issues.

¿Have u seen the image? if u cant understand why your plugins lacks of customaztion-gui, then, i assume im wasting my time.

**Comment by PyvesB** [comment]
> Start by repairing the damage you've done, showing support to the project and writing well-formed feature requests, rather than duplicating unintelligible messages across several issues.

**Comment by PyvesB** [comment]
> Look, i was aggresive and disrespectful, i admit that and i appoligze for that.

Did you actually mean this? The very next day you're engaging in spam, aggressive and disrespectful behaviour **_again_**.
