### ISSUE TITLE
Color of the plugin not working everywhere

### ISSUE THREAD

**Issue by pdrbohlav** [PyvesB/advanced-achievements#839]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.0
* Minecraft version: Paper 1.16.2
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:beetle: **Description**

The plugin color does not work on 3 spots:

1. When you have completed the achievement, the actual date below "Reception date:" stays purple no matter what I do with config or messages.
2. The same as previous, just with the "Reward:" section. When the achievement is completed, the dot infront of the lines stays purple.
3. I guess this one isn't a bug, rather a feature - I'd like to be able to change the color of the text below "Description:", right now it's always gold for completed achievements (maybe a separate color from the plugin color). --------- Figured this is the actual message color, so I can just change it and it's fine. You can ignore this part.

**Comment by PyvesB** [comment]
Hi @pdrbohlav,

That's odd, could you please share a screenshot showing issues 1 and 2?

**Comment by pdrbohlav** [comment]
The purple color that doesn't wanna change:
![image](https://user-images.githubusercontent.com/16155568/92331543-bc59d600-f077-11ea-94d9-3899b07ec0a3.png)

Uncompleted achievement with correct color:
![image](https://user-images.githubusercontent.com/16155568/92331563-e3180c80-f077-11ea-8136-beaa2acae098.png)

**Comment by PyvesB** [comment]
Starting with Spigot 1.16, it seems that lore lines have been rendering as purple by default. Advanced Achievements is not setting that purple colour in the shared screenshots. I've raised a Spigot issue [here](https://hub.spigotmc.org/jira/browse/SPIGOT-6126), as I'm hoping it can be resolved without yet another workaround in Advanced Achievements.

**Comment by PyvesB** [comment]
By the way, feel free to vote or comment on the Spigot issue I linked above, it's more likely it will get attention. 😉

**Comment by PyvesB** [comment]
It's been many weeks without any news from the Spigot team, so I've gone ahead and implemented a workaround in Advanced Achievements. The good news is that it was easy enough and doesn't add more code complexity. 🎉
