### ISSUE TITLE
2 General Questions for Setup

### ISSUE THREAD

**Issue by CptPICHU** [PyvesB/advanced-achievements#841]
* Advanced Achievements version: 6.2.0
* Minecraft version: 1.16.22
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: YES
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: YES

:question: 2 General Questions

Hi there!
I'd like to ask two questions. Is there a possibility to play a sound when an achievement is earned?
And 2nd: Is there a way to track status effects? I for example would like to give an achievement when a certain distance is traveled using the levitation effect. It would be awesome if you could help me!

-CptPICHU

**Comment by PyvesB** [comment]
Hello @CptPICHU,

Two possibilities when an achievement is received:
* a firework is shot -> the blast noise would likely interfere with any other sound that was played at the same time.
* switching `SimplifiedReception` in _config.yml_ -> a calm sound will be played without any firework.

Unfortunately, I don't think there currently is a way to track levitation. I didn't even realise this was a thing, I'm not really up-to-speed with the latest releases of the game. :)

**Comment by CptPICHU** [comment]
Thank you so much! I found another workaround.
Well i could in fact just play a sound using a command as reward. As simple as that :) But thank you anyways.
Maybe you could implement trackers for effects in the future? This would be pretty cool as i think.

Have a nice day!

**Comment by PyvesB** [comment]
> Thank you so much! I found another workaround.
> Well i could in fact just play a sound using a command as reward. As simple as that :) But thank you anyways.

Yep, that's a clever solution! Out of interest, is there a native Minecraft/Spigot command to play sounds, or are you using another plugin?

> Maybe you could implement trackers for effects in the future? This would be pretty cool as i think.

I suggest putting a message in #153: that issue collates quite a few category suggestions, from time to time one of them is picked up and implemented. :)
