### ISSUE TITLE
Request Boss plugin Support

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#842]
* [x] AA v6.2.1
* [x] MC v1.16.2 paper
* [x] Read through Wiki
* [x] Not really an existing issue

Since this plugin is now paid premium, would you add Boss plugin support now, please?

**Comment by PyvesB** [comment]
Hi @BobbyMere,

Duplicate of #623, closing this one as there's little point in having multiple issues about the same feature request. :wink:
