### ISSUE TITLE
How To Add Prefix and Suffix 

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#843]
* [x] AA v6.2.1
* [x] MC v1.16.2 paper
* [x] Read through Wiki
* [x] Not exactly a bug
Hello! I'm wondering how you add the prefix and suffix to achievements in messages as shown on the main page. I've searched through the lang.yml and the config and figure this out. Thanks 
<img width="527" alt="Screenshot 2020-09-13 070013" src="https://user-images.githubusercontent.com/25316276/93017520-0585ba80-f58f-11ea-9b1a-ea975d3247c0.png">

**Comment by PyvesB** [comment]
Hi @BobbyMere,

Ah yes, that's a fun one, I remember configuring that years ago. Will do some experimenting tomorrow and try to come back to you with the solution. 😉

**Comment by PyvesB** [comment]
When I tried this years ago, newline characters `\n` worked in chat messages, but that no longer seems to be the case in Spigot 1.16. You can still kind of get it working: for the prefix, pad the message with a prefix of the right size, e.g. `achievement-new: '============= Achievement received ============= [☘] New Achievement:'`. Similar for the reward messages by putting the suffix at the end.

**Comment by BobbyMere** [comment]
Thanks for replying to this. I'll figure something out
