### ISSUE TITLE
How To change Gui Category Color

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#844]
* [x] AA v6.2.1
* [x] MC v1.16.2 paper
* [x] Read through Wiki
* [x] Not a bug

I can't figure out how to change the category color. They're dark gray and I'm wondering if you could help me figure out how to change it. 

It looks like this 
<img width="191" alt="Screenshot 2020-09-13 101313" src="https://user-images.githubusercontent.com/25316276/93021745-1859b880-f5aa-11ea-9381-b2ec56fc47e9.png">

I would like "Fish Caught" be the a different color other than Dark Gray

Thank you

**Comment by PyvesB** [comment]
Hello @BobbyMere, you can simply modify the `ListAchievementFormat` configuration parameter, for example set it to `'§2%NAME%'`.

**Comment by BobbyMere** [comment]
Thank you
