### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by PortableGames** [PyvesB/advanced-achievements#845]
i pay 9.99 euro and cant download from spigot ! https://ctrlv.cz/NMfZ https://ctrlv.cz/7eoE

**Comment by PyvesB** [comment]
Hi @PortableGames,

Sorry to hear about that. I can't yet see the transaction on my side. I suggest we wait till tomorrow if that's okay, it may take some time depending on the currency. :wink:

**Comment by PortableGames** [comment]
I have a lot of purchased plugins always it was possible to download the plugin immediately after payment

**Comment by PyvesB** [comment]
Things seem to have sorted themselves out, could you please confirm?

**Comment by PortableGames** [comment]
confirmed ;)
