### ISSUE TITLE
Database Conversion Command

### ISSUE THREAD

**Issue by IgnisCraft** [PyvesB/advanced-achievements#846]
I am one of many who I'm sure would like a command to convert our sqlite data to MySQL. I asked the Author on Spigot and was told pretty much no, but now there is a premium version so I'd like to propose that I will personally buy premium for this feature and donate extra. I don't want to sit there converting 100s of users data to a database, I have much more important things to be doing on the server. This feature would make this plugin worth the $10.

**Comment by PyvesB** [comment]
Hi @IgnisCraft,

As indicated in the past, there are many tools that do the conversion automatically, you really don't need to sit there for very long. There's little point in adding database conversion complexity to Advanced Achievements if it already exists in tools built for that specific purpose. 😉
