### ISSUE TITLE
Question: Progress Bar Color Change

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#849]
* [x] AA v6.2.1
* [x] MC v1.16.2 paper
* [x] Read through Wiki
* [x] Not a bug

Hello! I can't figure out how to change the progress bar color. I see there's `ListColorNotReceived: 8` but can't find the one for the progress bar. I'm hoping to change it from orange to some other color.
<img width="301" alt="Screenshot 2020-09-15 071338" src="https://user-images.githubusercontent.com/25316276/93208957-fe8fb100-f722-11ea-8fd8-3dca1fe2f1b9.png">
.

**Comment by PyvesB** [comment]
Hello @BobbyMere,

The filled up part of the progress bar is governed by the `Color` parameter in _config.yml_, the non-filled up part is governed by `ListColorNotReceived`. 😉
