### ISSUE TITLE
/pl seems to be kicking me out. (probably spigot bug in 1.16.1)

### ISSUE THREAD

**Issue by mrfloris** [PyvesB/advanced-achievements#852]
:information_source: **Basic information**

* Advanced Achievements version: 6.3.0.premium
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: no. i did not, only 35%
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes, couldn't find alike issue open

:beetle: **Description**

typing /pl in-game kicks me out, showing probably stuff related to chat component / hex colors

:page_facing_up: **Server logs** (it says nothing just shows me typing /pl

![Screenshot 2020-09-16 at 18 53 46](https://user-images.githubusercontent.com/28841349/93368414-42330980-f84e-11ea-905d-5f5c20bf38c1.png)

I suspect upgrading to 1.16.3 will probably fix this, but we're not (yet) in the position to do so, i thought i'd report this at least if there's a way to update the premium plugin to perhaps prevent this from happening in 1.16.1

**Comment by PyvesB** [comment]
Hello @mrfloris,

Yes, this looks like a known bug in Spigot, I see you reacted in [SPIGOT-6056](https://hub.spigotmc.org/jira/browse/SPIGOT-6056). Other problems with Gson parsing were also flagged up in #769, generally speaking 1.16 broke a lot of things.

Is upgrading to a more recent build of 1.16.1 or 1.16.2 possible? It may well fix the issue. I'm running 1.16.2 from a couple of weeks back, I'm not able to reproduce. Though for some reason I don't get any hovers when running `/pl`, not sure whether it's expected.

I don't think there's much I can fix from my side, looking at your screenshot, I think the server is pulling the values from the _plugin.yml_ (https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-plugin/src/main/resources/plugin.yml), I'm not actually setting colours in there as you'll notice. I'm really not sure why things are blowing up. :confused:

**Comment by mrfloris** [comment]
Since it's only operators that do /pl, it's not a super issue. Thanks for the swift response. We will do further attempts to properly convert to 1.16.3 soon. Hopefully that resolves it.

**Comment by PyvesB** [comment]
No worries! I also voted on the Spigot issue - not sure how much they care about votes though.
