### ISSUE TITLE
[Premium] No gui?

### ISSUE THREAD

**Issue by msmanui** [PyvesB/advanced-achievements#855]
Hello!

So u make the plugin premiu, so i was really excited because i thought u had new gui full customzation but nope. Still is the same gui lacking of basic features that i have already explained many times. 
I still i dont get it why u cant add such basic features.

**Comment by PyvesB** [comment]
> Hello!

Hello @msmanui,

> So u make the plugin premiu

Unsure how this is relevant to the discussion.

> so i was really excited because i thought u had new gui full customzation but nope

Unsure what led you to think that. The plugin's changelogs are generally clear and carefully polished, at the time of writing the last one that highlights changes to GUI customisation is for version 6.1.0. Maybe you didn't read them or you're mixing things up with a different plugin? Either way, I would strongly encourage you consult all changelogs, especially as they're readily available in multiple locations (Spigot and GitHub). 

> Still is the same gui lacking of basic features that i have already explained many times.

I have not seen no such explanations. All your previous messages were malformed, unconstructive and rude, you even admitted that yourself. Consequently, I never actually read past the first one or two sentences. I've honestly got no idea what you want at this point. The title of the issue, "No gui?", suggests that you're not aware that there is already a GUI in the plugin. Try out _/aach list_, as described in the homepage, Wiki and in-game help. I'm quite surprised you managed to miss it though, so maybe the title is just confusing.

> I still i dont get it why u cant add such basic features.

Unsure what you mean by this, it doesn't sound constructive anyway.

If you are aware that the plugin already features an extensively customisable GUI, but you have constructive suggestions to improve it, I suggest you raise a proper feature request following the issue template, written in decent English without use of SMS language, clearly explaining what your idea is. If it seems like a good idea and other users ask for it, myself or another contributor might find some time to give it a go in the future. 😉
