### ISSUE TITLE
Lack of gui customaztion. 

### ISSUE THREAD

**Issue by msmanui** [PyvesB/advanced-achievements#858]
Hello!

Here is lot things u cant do and also i've uploaded a photo of how it could be implemented:
- You cant change specific material for each achivement.
- You cant hange the style of the description of each achievement
- You cant change the order/slot of achivements

![fefe](https://user-images.githubusercontent.com/63617395/93932308-5b2c3680-fcf6-11ea-97be-ff91455d2d83.png)

**Comment by PyvesB** [comment]
Hello @msmanui,

>     * You cant change specific material for each achivement.

I've already responded to you in #609 regarding this suggestion, so won't repeat myself.

>     * You cant change the order/slot of achivements

You can: reorder the category names in _gui.yml_ to change their order in the main GUI, and reorder the sub-categories in _config.yml_ to change their order in the category GUIs.

>     * You cant hange the style of the description of each achievement

You can do that as well, but I'm guessing you want something more like the screenshot you shared. I think that's reasonable. No timelines, but I may look into it at some point, especially if users who have purchased the premium version think it's a good idea. 😉

**Comment by msmanui** [comment]
> Hello @msmanui,
> 
> > ```
> > * You cant change specific material for each achivement.
> > ```
> 
> I've already responded to you in #609 regarding this suggestion, so won't repeat myself.
> 
> > ```
> > * You cant change the order/slot of achivements
> > ```
> 
> You can: reorder the category names in _gui.yml_ to change their order in the main GUI, and reorder the sub-categories in _config.yml_ to change their order in the category GUIs.
> 
> > ```
> > * You cant hange the style of the description of each achievement
> > ```
> 
> You can do that as well, but I'm guessing you want something more like the screenshot you shared. I think that's reasonable. No timelines, but I may look into it at some point, especially if users who have purchased the premium version think it's a good idea. 😉

Im just asking a customazation like in the screenshot, that way the gui would be 100% customizable. If the premium version would be that way i would gladly buy it. In that way, any user could customize the way HE wants. 
Thanks for understanding

**Comment by msmanui** [comment]
PyvesB, are u planning to add this customazation in a future?

**Comment by PyvesB** [comment]
> No timelines, but I may look into it at some point, especially if users who have purchased the premium version think it's a good idea.

**Comment by n54b** [comment]
pour sa, je pense que tu devrais revoir une bonne partie de ton code :S je me suis penché dessus pour juste ajouté un "sous-menu" du style : Jobs => Choisis le métier ou tu veux voir les succès => Succès du métier en question
mais franchement c'est hard pour moi le java ^^

for that, I think you should revise a good part of your code :S I've looked at it to just add a "sub-menu" like: Jobs => Choose the job or you want to see the successes => Success of the job in question
but frankly it's hard for me the java ^^

**Comment by YuriTheMan** [comment]
> * You cant change specific material for each achivement.
> 
> * You cant hange the style of the description of each achievement
> 
> * You cant change the order/slot of achivements

i can do all three, i'm pretty sure you're not using the latest version of aach.

the screenshot looks like a complete mess, all those nested yaml lists and placeholders are a guaranteed recipe for disaster and battling to get the syntax right.  plus, you would need at least five different ones for every single aach, one style for received, one for in progress, one for not started, one for obfuscated and one for locked. i don't want to have to add thousands and thousands of lines of clunky config, the gui is already 100% customizable. @PyvesB please leave things as they are, msmanui obviously did not think about this for more then 30 seconds and can't even spell achievement correctly.

long time user of the plugin, thanks for the great work over the years!

- yuri

**Comment by PyvesB** [comment]
You raise some good points @YuriTheMan ! This issue has already received quite a few downvotes and there's probably not much else to add, I'll go ahead and close it. 😉

**Comment by msmanui** [comment]
> > * You cant change specific material for each achivement.
> > * You cant hange the style of the description of each achievement
> > * You cant change the order/slot of achivements
> 
> i can do all three, i'm pretty sure you're not using the latest version of aach.
> 
> the screenshot looks like a complete mess, all those nested yaml lists and placeholders are a guaranteed recipe for disaster and battling to get the syntax right. plus, you would need at least five different ones for every single aach, one style for received, one for in progress, one for not started, one for obfuscated and one for locked. i don't want to have to add thousands and thousands of lines of clunky config, the gui is already 100% customizable. @PyvesB please leave things as they are, msmanui obviously did not think about this for more then 30 seconds and can't even spell achievement correctly.
> 
> long time user of the plugin, thanks for the great work over the years!
> 
> ~ yuri

You need to review your concept of "customizable". This plugin isnt customizable. 
There are 2 kind of people in spigot, the one who wants all easy or the one who wants to customize everything. I've a professional network and so all my designs are intended to be that way. With this plugins isnt possible.
