### ISSUE TITLE
[Question] Advancement tab?

### ISSUE THREAD

**Issue by TheRobLP** [PyvesB/advanced-achievements#859]
:information_source: **Basic information**

* Advanced Achievements version: None
* Minecraft version: Paper 1.16.3
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:question: **Help request**

Hello. I have a question about the premium version of this resource. Is it possible with this resource to create custom advancement tabs on 1.12+ servers? 

(example of what I mean by that: https://static.planetminecraft.com/files/resource_media/screenshot/13093258-screenshot.png ). 

I´ve been searching for something which can do that, and some pictures in your resource let me believe that may be the case. But I want to make sure. Thank you in advance for any replies.

:wrench: **Configuration**

None

**Comment by PyvesB** [comment]
Hello @TheRobLP ,

Minecraft's native advancement GUI is unfortunately not very flexible and there isn't even a proper Spigot API to interact with it. Advanced Achievements will create one additional tab in it with all its own achievements replicated as advancements in a semi-organised tree.

Aside from that, Advanced Achievements has its own inventory-like GUI which provides much more flexibility and customisation options.

Hopefully this answers your questions. 😉
