### ISSUE TITLE
MySQL Database

### ISSUE THREAD

**Issue by hellot1m** [PyvesB/advanced-achievements#860]
:information_source: **Basic information**

* Advanced Achievements version: 6.4.0
* Minecraft version: 1.16.3
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Can't find MySQL support in wiki
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:question: **Help request**

I am unable to get Advance Achievements to connect to my mysql server. i noticed in the database section there is no spot for database name or SSL info. i have adjusted all the fields beyond "prefix" but it still won't connect. I have 6 other plugins i am using mysql for without any issues. the config here is probably the weirdest setup of all plugins i've seen for database configuration setup.

:wrench: **Configuration**

````
# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: false

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: mysql

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ''

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ''

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: xx.xx.xx.xx
DatabaseUser: root
DatabasePassword: xxxxxxxx

````

**Comment by PyvesB** [comment]
Hello @hellot1m,

You can specify the database name in the address. For example: `jdbc:mysql://xx.xx.xx.xx:5432/my-database-name`. What other parameters do you need to specify?

**Comment by hellot1m** [comment]
Thanks! i got it. I have just never seen this type of format before when specifying the database. Typically its got its own line with something like `database:`

**Comment by PyvesB** [comment]
Glad to hear it works!

At the very beginning, Advanced Achievements was a rewrite of https://github.com/deathmarine/Achievement . That's where that parameter format originally came from. May improve it at some point, though backwards compatibility it always the tricky bit with these kind of things. :)
