### ISSUE TITLE
Cant connected mysql Database

### ISSUE THREAD

**Issue by ionixxz** [PyvesB/advanced-achievements#871]
I am not able to connected a database to your plugin I have configured the database and everything and every single time I upload it into your plugin it says cant connected to database im using mysql

Also there is nothing wrong with my database I have about 15 plugins running on their own databases without issues just having an issue with your plugin that I purchased

Please let me know what I can do

Thanks

ionixxz

:information_source: **Basic information**

* Advanced Achievements version: 
* Minecraft version: 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 

:question: **Help request**

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @ionixxz! 👋🏻 

Does #860 shed any light on your issue?

**Comment by ionixxz** [comment]
I had my server dev try and myself and each time it says can't connect to database would you be ok with a discord chat if possible to add you there maybe both of us are missing a step

**Comment by PyvesB** [comment]
> Does #860 shed any light on your issue?

Additionally to the one above, two more questions: what does you database configuration look like? What is the exact error you get from the plugin?

**Comment by ionixxz** [comment]
sorry for such a long reply

We actually removed the database and went to default but it did do something else today the plugin

My staff member removed some achievements and it reverted the config file to default everything was reset

Id be happy to show you how I am doing on the backend if you have discord and we can speak on that as a screen share

https://discord.gg/SQH3pr6

this is for my discord no one is really on it except me

Thanks for your time

**Comment by PyvesB** [comment]
Sorry, I don't generally use Discord, I suggest we continue here.

If the config got reverted, you probably ended up with something that was invalid YAML. The previous version with the achievements removed should still be contained in _config.yml.bak_. As suggested in the config's header, paste that in http://yaml-online-parser.appspot.com to make sure that you've still got a valid file. 😉

**Comment by ionixxz** [comment]
If I send you my database info minus the password and your database info can you place my stuff into your code and I will copy and paste it how you do it we use MySQL this way your the expert and should work when i insert it into my server

Please

**Comment by PyvesB** [comment]
Ah, so back to the database!

Sure, simply paste the database configuration section here, making sure you remove the credentials.

**Comment by PyvesB** [comment]
It's been over a month now, and even the very minimum basic information from the issue template is still missing. Unfortunately, I have no choice but to close.
