### ISSUE TITLE
problems with /aach generate

### ISSUE THREAD

**Issue by DeadDre4mer** [PyvesB/advanced-achievements#883]
:information_source: **Basic information**

* Advanced Achievements version: 6.6.2
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes, but I can't understand anything

:question: **Help   request**
Hello! Please, help me D: 
I just typed command /aach generate and saw in chat "An internal error occurred..." (I attached all screenshots), the command failed and a lot of error lines appeared in the console. I tried to find a solution on the Internet, but since English is not my native language my attempts were in vain, so please, can you explain to me what am I doing wrong. 

:wrench: **Configuration**
![1](https://user-images.githubusercontent.com/73438361/97457742-175acb80-194b-11eb-86e0-9d6dbffcf9a5.png)
![2](https://user-images.githubusercontent.com/73438361/97457747-188bf880-194b-11eb-9e5c-12c9781c64f8.png)
![3](https://user-images.githubusercontent.com/73438361/97457749-19248f00-194b-11eb-8e7b-24bc23cdfe6c.png)
![4](https://user-images.githubusercontent.com/73438361/97457754-19bd2580-194b-11eb-92da-e02d209ab17c.png)

````
````

**Comment by PyvesB** [comment]
Hello @DeadDre4mer ! 👋🏻 

See #769. This is basically a known problem with early 1.16 Spigot/PaperSpigot builds, updating to the latest 1.16.3 version should solve the problem. 😉 

Let me know if you still have issues after the upgrade!
