### ISSUE TITLE
Placeholder for '/aach give' achievements?

### ISSUE THREAD

**Issue by 27chandler** [PyvesB/advanced-achievements#885]
:information_source: **Basic information**

* Advanced Achievements version: 6.6.0
* Minecraft version: 1.16.3
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:question: **Help request**

Is there a placeholder for a command base achievement? I have a few achievements that are given using "/aach give achievementname PLAYER" and I wanted to display some details about if the player has them in a different plugin that's placeholder API compatible.

I tried the %aach_playercommands_[command]% placeholder but it only works for command the player has run directly, and not achievements given via the "/aach give" command.

:wrench: **Configuration**

This is the command based achievement I was trying to placeholder
````
Commands:
  blockoftruth:
    Goal: Find the hidden block of truth!
    Message: You found the block of truth!
    Name: block_of_truth
    DisplayName: Block Of Truth!
````

**Comment by PyvesB** [comment]
Hello @27chandler! 👋🏻 

Unfortunately no, there is no current placeholder support for the _Commands_ category. #789 was supposed to add one, but the author stopped responding at some point so it never got merged in. 😕

**Comment by 27chandler** [comment]
Do you think I could achieve the same functionality with the custom achievement type, since those do currently have a placeholder. And then I use the /aach add command to award them?

**Comment by PyvesB** [comment]
That would probably work, yes! Worth giving it a try and seeing what works best for you. 😉

**Comment by 27chandler** [comment]
I can confirm that using the custom category instead worked. I'll close the issue.
