### ISSUE TITLE
Changement de pseudo

### ISSUE THREAD

**Issue by organizatsiya** [PyvesB/advanced-achievements#890]
```
organizatsiya commented on 7 Jul
Bonjour,

Je ne sais pas si c'est déjà possible car je n'ai rien trouvé dans les commandes.
Pouvoir transférer l'ensemble des challenges d'un pseudo vers un autre serait une évolution très utile.
```
```
PyvesB commented on 8 Jul
Bonjour @organizatsiya,

Si c'est seulement un changement de pseudo avec le même compte, le transfert n'est pas nécessaire,
 le plugin utilisant l'identifiant de compte pour stocker les données. 😉
```
Je viens de mettre mon serv en production.
En effet , le plugin prend en compte l'uuid du compte mais quand un joueur joue en version crack, cette fonctionnalité ne fonctionne pas bien évidemment

**Comment by PyvesB** [comment]
Si les versions crackées ne fonctionnent par correctement et ne respectent pas les contrats de base de l'API Bukkit (i.e. la même personne conserve toujours le même UUID), la seule solution serait de migrer les statistiques manuellement via les commandes _/aach add_ et _/aach give_. Une requête SQL sur la base données ferait l'affaire également.

**Comment by organizatsiya** [comment]
Ne serait il pas possible d'ajouter une commande du genre _/aach playercopy uuid(origine) uuid(destination)_ qui permettrait de copier directement un profil vers un autre dans achievements.db ?

**Comment by PyvesB** [comment]
Techniquement possible, mais pas quelque chose que je compte implémenter moi-même. Si quelqu'un prépare un pull request de qualité, je peux le revoir.
