### ISSUE TITLE
Custom Head 

### ISSUE THREAD

**Issue by n54b** [PyvesB/advanced-achievements#891]
Add the support of CustomHead
Ajouter le support de tête custom 

>> https://minecraft-heads.com/

I know that some plugin uses the "VALUE"
Je sais que certain plugin utilise la "VALUE"

this can, perhaps help 
(ceci peut, peut être aider > https://www.spigotmc.org/threads/custom-heads-texture-value.329524/ )

(PyvesB Français ?)

**Comment by PyvesB** [comment]
Hello @n54b!

Simply use the custom display name, that will work for all _Places_ achievements. See  #708 where this was implemented. 😉 

(Français ? Mais qu'est-ce que c'est que ça ?? :p)

**Comment by n54b** [comment]
Je veux dire tu es français ? ^^

**Comment by PyvesB** [comment]
> Je veux dire tu es français ? ^^

Oui, à moitié :)

**Comment by n54b** [comment]
Ah oki ^^ tu me diras si tu préfères que je fasse mes ticket en anglais ou en francais :p 

Question : /aach list "name achievement" => Tu crois qu'il est possible de séparer les achievements dedans ? Par exemple 
JobsReborn j'utilise plusieurs métiers, il est possible de crée un SOUS-MENU ? 
Car j'ai 100 niveaux par métiers et sa fait un peu beaucoup d'achievement dans une seule catégorie :p

**Comment by n54b** [comment]
BUG : J'ai crée mon yml de cette manière : 

    101:
      Goal: Gagne un niveau de Chasseur !
      Message: Tu as atteint le niveau 100 en chasseur !
      Name: jobsreborn_101_chasseur
      DisplayName: Level up chasseur
      Type: normal
      Reward:
        Item: bow 9
  Paysan:
    1:
      Goal: Gagne un niveau de Paysan !
      Message: Tu as atteint le niveau 2 en paysan !
      Name: jobsreborn_1_paysan
      DisplayName: Level up paysan
      Type: normal
      Reward:
        Command:
          Execute: 'say §7ALERT: §4PLAYER§7 has become the §4STONE GOD§7!'
          Display: Become the Stone God!

L'achievement de paysan m'est totalement bloqué ... 
![image](https://user-images.githubusercontent.com/12047619/98672099-8c6bcf00-2355-11eb-98ae-ef291e38aba7.png)

**Comment by PyvesB** [comment]
> Ah oki ^^ tu me diras si tu préfères que je fasse mes ticket en anglais ou en francais :p

Futurs tickets en Anglais, comme ça je peux facilement les référencer et ils peuvent être utiles à un plus grand nombre. :wink:

> Question : /aach list "name achievement" => Tu crois qu'il est possible de séparer les achievements dedans ? Par exemple
> JobsReborn j'utilise plusieurs métiers, il est possible de crée un SOUS-MENU ?
> Car j'ai 100 niveaux par métiers et sa fait un peu beaucoup d'achievement dans une seule catégorie :p

Pas possible de faire des sous-menus, mais tu peux utiliser le nouveau paramètre `Type` pour avoir des icônes différentes pour chaque métier.

**Comment by PyvesB** [comment]
> BUG : J'ai crée mon yml de cette manière :
> 
> ```
> 101:
>   Goal: Gagne un niveau de Chasseur !
>   Message: Tu as atteint le niveau 100 en chasseur !
>   Name: jobsreborn_101_chasseur
>   DisplayName: Level up chasseur
>   Type: normal
>   Reward:
>     Item: bow 9
> ```
> 
> Pecheur:
> 1:
> Goal: Gagne un niveau de Pecheur!
> Message: Tu as atteint le niveau 2 en pecheur !
> Name: jobsreborn_1_Pecheur
> DisplayName: Level up Pecheur
> Type: normal
> Reward:
> Command:
> Execute: 'say §7ALERT: §4PLAYER§7 has become the §4STONE GOD§7!'
> Display: Become the Stone God!
> 
> L'achievement de paysan m'est totalement bloqué ...
> ![image](https://user-images.githubusercontent.com/12047619/98672099-8c6bcf00-2355-11eb-98ae-ef291e38aba7.png)
> 
> Edit 3 : J'ai tester de mettre une tete custom dans GUI mais non il me rollback la config...

Je ne comprends pas le problème, qu'essayes-tu de faire ?

**Comment by n54b** [comment]
Je vais résumé : 

BUG  :

Avec le support de jobs reborn, si je met 2 jobs en achèvement , je ne peux en faire qu'un type exemple : Jobs Pecheur & Chasseur, il me prend uniquement le job chasseur !
--------------------------------------------------------------------------------------------------------
BUG / AMÉLIORATION ? :

Impossible de mettre une tête à la place des boutons suivant/précédent
--------------------------------------------------------------------------------------------------------
Amélioration : 

Pouvoir crée des sous catégorie ou par exemple jobsreborn_pecheur jobsreborn_mineur etc..., crée des "catégorie principal" pour jobs reborn spécifique à chaque métier.

**Comment by PyvesB** [comment]
> Avec le support de jobs reborn, si je met 2 jobs en achèvement , je ne peux en faire qu'un type exemple : Jobs Pecheur & Chasseur, il me prend uniquement le job chasseur !

Je n'ai toujours pas compris. Qu'est-ce que faire des types ou prendre des jobs veut dire ? Sans doute plus simple de partager l'intégralité de _config.yml_ et _gui.yml_ et m'indiquer quelles actions je dois faire pour reproduire. :)

**Comment by n54b** [comment]
Voici : 
Config.yml
http://pastebin.fr/72612
Gui.yml
http://pastebin.fr/72613

**Comment by PyvesB** [comment]
Le job doit être spécifié en lettres minuscules, essaye `pecheur` et dis-moi si ça résout le problème. 😉

**Comment by n54b** [comment]
Déjà testé et rien qui change :(

**Comment by PyvesB** [comment]
Peux-tu me donner le nom exact du job, comme il apparaît en jeu?

**Comment by n54b** [comment]
![image](https://user-images.githubusercontent.com/12047619/98994557-4d45a580-2530-11eb-8ccd-5e35f416a366.png)

**Comment by PyvesB** [comment]
Bon, je ne sais pas d'où vient le problème à première vue, je regarderai plus en détails ce weekend. Là j'ai surtout besoin de sommeil :)

**Comment by PyvesB** [comment]
Ça serait utile que j'ai ta configuration de JobsReborn, j'ai jamais vraiment utilisé le plugin donc je tâtonne. 😉

**Comment by n54b** [comment]
Je t'envoie sa immédiatement (désolé du retard le weekend fut chargé ^^) 
https://pastebin.com/NY6hu9Jq

**Comment by PyvesB** [comment]
Tout marche bien de mon côté. A condition de bien spécifier le job en minuscules dans la configuration d'Advanced Achievements comme indiqué par https://github.com/PyvesB/advanced-achievements/issues/891#issuecomment-726315988, je peux recevoir le succès:
![2020-11-16_19 30 15](https://user-images.githubusercontent.com/10694593/99299103-a8361000-2842-11eb-8831-4a00ed8b53b2.png)

**Comment by n54b** [comment]
(désolé du retard de réponse, j'étais partie sur totalement autre chose je fini la configuration de mon autre plugins et je m'attaque à nouveau a aach et jvais avoir du boulot la :p

**Comment by PyvesB** [comment]
Bon, je ferme pour le moment, si tu as encore des problèmes, je peux rouvrir ou tu peux créer de nouveaux tickets - ça coûte rien et c'est plus facile de gérer de petits tickets avec un cadre précis. 😉
