### ISSUE TITLE
analyse de la base de données

### ISSUE THREAD

**Issue by organizatsiya** [PyvesB/advanced-achievements#893]
Bonjour

I would like to know how the dates are coded in the achievements.db database and if it is possible to find the date of a successful challenge.
For example, how to find the date from "1603583096718"

cordialement

**Comment by PyvesB** [comment]
Bonjour @organizatsiya ! 👋🏻 

That number follows the [Unix epoch](https://en.wikipedia.org/wiki/Unix_time) format, it corresponds to the number of milliseconds since January 1st 1970. 😉

**Comment by organizatsiya** [comment]
Bonjour,

thanks a lot for this information.

**Comment by PyvesB** [comment]
No worries. :)
