### ISSUE TITLE
Toggle per rarety achievement notification

### ISSUE THREAD

**Issue by RomainFrost** [PyvesB/advanced-achievements#894]
:information_source: **Basic information**

* Spigot username: RomainFrost

:clipboard: **Description**

Hello ! First, I must say the plugin is really good and I used it for a while now. I am using it for a server and I was wondering if it was possible to add a way to do `/aach toggle [all/normal/rare/...]` for some players who don't want to be notified at all or just by easy achievements.

I hope my english isn't too bad.

Have a nice day !

Romain

**Comment by PyvesB** [comment]
Hello @RomainFrost! 👋🏻 

The `Type` parameter is currently an internal configuration value, it's hidden to them. How would they know which values are possible and what they correspond to? I'm wondering whether this feature may be confusing because of this. :)

**Comment by RomainFrost** [comment]
Thank you for the quick reply !

I want to add achievements difficulty/rarety on my server. The idea is that an achievement which is easy to realize would be categorized as an easy achievement, same for normal difficulty, hard and hardcore. As there are many achievements, it would be nice that player can disable achievements' notifications depending of the difficulty and keep only the hard one for example.

**Comment by PyvesB** [comment]
Okay, I'll see what I can do.

**Comment by PyvesB** [comment]
I've implemented the requested feature, e.g. `/aach toggle rare`. As the Type parameter will be an internal hidden parameter for most cases, I've purposefully not included the `Type` values in the in-game completion proposals, but that shouldn't matter too much in you case as all values are public. 😉
