### ISSUE TITLE
Will this work for a reward for completing every quest

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/advanced-achievements#895]
Hey I am just wondering if this format will work for the AllAchievementReceivedRewards section:

![image](https://user-images.githubusercontent.com/46936647/99882522-f8cdb480-2c18-11eb-9bc4-643402293960.png)

**Comment by PyvesB** [comment]
Hello @JHarris12345 ! 👋🏻 

Yes, I believe that should work fine. 😉
