### ISSUE TITLE
Добавление, улучшения категорий 

### ISSUE THREAD

**Issue by JudgeVlad** [PyvesB/advanced-achievements#896]
I have a problem in improving the AdvancedAchievements plugin I want to make it so that there were two picks, clicking on one pick was the quest to break the stone, and on the other was the quest to break the mycelium. I write everything in config. yml, in the end it turns out that by clicking on the pickaxe, my goal is to break 300 mycelium. Question how to do it
1)Two picks in the interface
2) clicking on one pickaxe was a quest to break the stone, and the other was a quest to break the mycelium.
![11](https://user-images.githubusercontent.com/74835691/99886123-34817200-2c4b-11eb-9a29-4c505ba44f41.PNG)
![22](https://user-images.githubusercontent.com/74835691/99886124-39462600-2c4b-11eb-89cd-3ca36a70d2e2.PNG)
![33](https://user-images.githubusercontent.com/74835691/99886126-3ba88000-2c4b-11eb-8af4-0d1427d712e9.PNG)
![44](https://user-images.githubusercontent.com/74835691/99886128-3e0ada00-2c4b-11eb-8232-923ec7dd2039.PNG)

**Comment by JudgeVlad** [comment]
Если могу дополнить.

**Comment by PyvesB** [comment]
Hello @JudgeVlad ! 👋🏻 

I'm not sure I fully understand - the Russian title and having ignored the issue template probably don't help. But this does seem like a duplicate of  #475.

**Comment by JudgeVlad** [comment]
> Здравствуйте @JudgeVlad ! 👋🏻
> 
> Я не уверен, что полностью понимаю-русский титул и проигнорировав шаблон вопроса, вероятно, не помогут. Но это действительно похоже на дубликат [№475](https://github.com/PyvesB/advanced-achievements/issues/475).

Нет, это не то.

**Comment by JudgeVlad** [comment]
Привет, @PyvesB 
Для более понятного объяснение своей проблемы, я нарисовал схему в paint, для меня это самый легкий способ.
Я бы хотел разделить категорию на две ячейки в интерфейсе для более приятной и легкой навигации, возможно ли это? если да, то вы могли бы написать как это сделать. Если будут еще вопросы пишите я попробую ответить на них.
P.s Пользуюсь переводчиков возможны проблемы в переводе.
![12](https://user-images.githubusercontent.com/74835691/100005696-6bd25900-2dda-11eb-95cc-faf5bf39e3d9.png)

**Comment by PyvesB** [comment]
Ok, gotcha. I think this is basically a duplicate of #536.

**Comment by JudgeVlad** [comment]
Hi, @PyvesB 
I may be wrong, but it's not like that.

**Comment by PyvesB** [comment]
If #536 was completed, it would technically allow users to mix and match achievements regardless of their parent category. So you could split the `Breaks` achievements into separate families in the GUI. That's what your picture is showing, isn't it?
