### ISSUE TITLE
Reward lore issue

### ISSUE THREAD

**Issue by SirCraftypants** [PyvesB/advanced-achievements#899]
Hi,

I use ultra permissions and i've added the command:

      Reward:
        Command:
          Execute: upc AddPlayerPermission PLAYER ebp.user.size.18     

This is the correct command for the permission so there's no problem with that but.

It is showing as Reward: Other

Is there a way i can change the word 'Other' to Permission and add lore to it?

I checked the Wiki but couldn't find a solution

Also can you make AA compatible with the following please.

Advanced Enchantments
Head Database
MyPet

**Comment by PyvesB** [comment]
Hello @SirCraftypants! 👋🏻 

Yes, I believe that's possible. [This part of the Wiki](https://github.com/PyvesB/advanced-achievements/wiki/Rewards#custom-commands) should hopefully shed some light on how to do so. 😉

**Comment by SirCraftypants** [comment]
Thank you, i hope one day AA will be compatible with the above plugins.
