### ISSUE TITLE
New settings for jobs reborn hook

### ISSUE THREAD

**Issue by Teyir** [PyvesB/advanced-achievements#903]
Hello,

Can you add a settings or a new catégorie for the plugin jobs reborn.

New catégorie: Jobs_Total

This new catégorie is for calculate all the level of jobs.

Exemple:

JobsRebornALL:
  ALL:
    10:
      Goal: Level 10 all jobs!
      Message: You have reached all jobs level 10!
      Name: jobsreborn_10_all
      DisplayName: All level 10
      Type: normal

Thank you very much :)

**Comment by Teyir** [comment]
( PAPI has a placeholder like that → **_%jobsr_user_totallevels%_**  )

ps: je viens de voire que vous parlez français, donc on peut communiquer en français si vous le souhaitez ;)

**Comment by PyvesB** [comment]
Hello/salut @Teyir ! 👋🏻 

A la base @n54b a implémenté la catégorie `JobsReborn`, peut-être que c'est quelque chose qu'il pourra rajouter ? :wink:

**Comment by n54b** [comment]
C'est aussi quelque chose qui m’intéresse mais ajouté le support de placeholder est très compliqué ...  Je ne suis pas assez bon dev pour faire sa ... en skript aucun problème mais en java ... 

It's also something I'm interested in but adding placeholder support is very complicated ...  I'm not good enough dev to do this ... in skript no problem but in java ...

**Comment by Teyir** [comment]
Effectivement ajouter le support de PlaceHolderAPI ça serais dingue, on pourrait faire nos propres catégories.

Je pense que vu l’ampleur du plugin il serait possible de demander de l'aider au dev de PAPI ou de d'autres personnes

**Comment by PyvesB** [comment]
Quelqu'un qui connaissait bien PlaceholderAPI avait commencé une implémentation dans #365, mais il n'y a jamais eu de suite. Un autre problème serait au niveau de l'interface _/aach list_ : tous les succès basés sur PlaceholderAPI feraient partie de la même catégorie, il faudrait #536 pour s'affranchir de cette limitation, et là encore c'est un gros, gros boulot !

**Comment by Teyir** [comment]
Oui effectivement,

Sinon on créé nos propres catégories, on met un ID etc...

Après c'est plus facile à dire qu'à faire évidement

**Comment by PyvesB** [comment]
> Sinon on créé nos propres catégories, on met un ID etc...

En parlant de ça, je suis en train de simplifier le code dans l'API pour que ça soit plus facile d'ajouter des catégories sans connaissances en Java. Je passerai un cup de cirage sur la documentation également.

**Comment by Teyir** [comment]
Super merci beaucoup :)

J'ai vraiment hâte de voire cette nouvelle maj

**Comment by PyvesB** [comment]
> En parlant de ça, je suis en train de simplifier le code dans l'API pour que ça soit plus facile d'ajouter des catégories sans connaissances en Java. Je passerai un coup de cirage sur la documentation également.

C'est fait dans la version 7.0.0. Au programme :
* le code Java nécessaire pour écrire un nouveau "listener" (classe en charge de traquer les événements pour la catégorie) a été légèrement simplifié.
* quand une nouvelle catégorie est définie, plus besoin de répéter les informations des fichiers de configuration dans le code Java en lui-même.
* plus besoin d’écrire du code Java pour que les anciens fichiers de configuration soient mis à jour pour la nouvelle catégorie : tout est désormais géré automatiquement.
* le temps nécessaire pour produire le JAR via Maven a été réduit de façon conséquente, ce qui devrait faciliter le test de la nouvelle catégorie en question.
* le [tutoriel pour implémenter de nouvelles catégories](https://github.com/PyvesB/advanced-achievements/wiki/Adding-new-categories) a été réécrit entièrement, avec pour objectif de guider un novice pas à pas.

En attendant, je vais fermer ce ticket, mais laisser #365 et #536.
