### ISSUE TITLE
Bug with giving max health reward

### ISSUE THREAD

**Issue by ArmonicPvP** [PyvesB/advanced-achievements#904]
:information_source: Bug with Max Health

* Advanced Achievements version: 6.7.2
* Minecraft version: Spigot 1.16.4
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes

:beetle: When giving out extra hearts as rewards, items that also give bonus health reset Advanced Achievements bonus health reward.

Give bonus max health thru reward, equip armor that also gives bonus health and remove armor

:page_facing_up: N/A

````

````

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @ArmonicPvP ! :wave:

Could you please edit your report and provide the following:
>     * Advanced Achievements version:

**Comment by ArmonicPvP** [comment]
I've updated it for you!

**Comment by PyvesB** [comment]
Thanks, just wanted to check that you were using a recent-enough version: old versions of the plugin used a deprecated version of the Bukkit API for handling max health. 😉 

Advanced Achievements 6.7.2 really doesn't do anything out of the ordinary when rewarding extra hearts. It calls the official Bukkit API by setting a new base value for `GENERIC_MAX_HEALTH`:
https://github.com/PyvesB/advanced-achievements/blob/4904e820e8f574c79fe8f834757708c60b73ef96/advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/PlayerAdvancedAchievementListener.java#L317

It never changes the player's health after that and doesn't keep track of any of the values as they are ultimately handled by the server.

If the player's health is being reset, it could either be:
* a bug in another plugin. You mentioned armor that gives bonus health, that's not a standard feature as far as I know. You should report the bug with the plugin that provides those custom capabilities.
* a bug with Spigot itself. You'll probably want to report it on [the Spigot issue tracker](https://hub.spigotmc.org/jira) in that case.

**Comment by PyvesB** [comment]
@ArmonicPvP did you manage to track down where the problem was coming from?

**Comment by PyvesB** [comment]
Feel free to share results of any bug reports you've raised with third-party projects when you get them. For now I can't see how I can assist you further, so I'll close this. :wink:
