### ISSUE TITLE
Translated plugin to Danish

### ISSUE THREAD

**Issue by Tobi-Jakka** [PyvesB/advanced-achievements#908]
Hey, so I translated the plugin to Danish, but I am not really sure how to contribute the file?

Would be nice if someone could explain to me how to do it or if I could just send it

- Tobi

**Comment by PyvesB** [comment]
If you navigate here[here](https://github.com/PyvesB/advanced-achievements/tree/master/advanced-achievements-plugin/src/main/resources), you should see an "Add File" button. Please call it _lang-DA.yml_.

Thanks in advance for submitting the translation. 😉

**Comment by Tobi-Jakka** [comment]
Thanks! Seems it didn't work because I was trying to upload a file. So I have made it now though I realised I made a silly mistake.
On line 4 the word "Gylden" Should be changed to "Gyldig".

- Tobi

**Comment by PyvesB** [comment]
No worries, I can fix the mistake afterwards. The next step for you is to navigate to https://github.com/Tobi-Jakka/advanced-achievements/tree/patch-1 and press the `Pull Request` button :)

**Comment by PyvesB** [comment]
Pull request merged and typo fixed in the commit above!
