### ISSUE TITLE
Disable Impossible Achievements from Default Config

### ISSUE THREAD

**Issue by strahil211** [PyvesB/advanced-achievements#916]
A good number of the Achievements are impossible to complete and this should not be in the default config.
Why? Server owners should not be expected to learn and be able to properly configure the plugin just so players are able to have a 100% completion rate.
A premium resource should work and be fully usable right off the bat.

For example, my players could not complete "Mario's Head" Without having a specific heads plugin. "Vote 10 Times" without having a voting features on the server. "Mythic killer" without having some mobs plugin. "No More DarkPyves" I don't even know why that's there. 

These are just a few I found to be impossible and I've had to manually remove them from the config so players can complete the achievements. Server owners should absolutely not have to do that to get this plugin to work fully on their server. Hence my request to have a more doable default Ach config.

**Comment by strahil211** [comment]
These "Impossible" Ach's should be optional and off by default and used as an example as to what owners can do with the plugin.

**Comment by TheCashFire** [comment]
I'm sorry but this wonderful developer has chosen to add a myriad of features in his plugin, including integration with other popular plugins, and the complaint that "I am an owner and I shouldn't have to work to understand this" is utter nonsense. He explicitly says in his notations in the plugin config that that they require an extra plugin to work, and if you don't want them active you can just _disable that category_ or _delete the unwanted achievement_. If you aren't willing to perform the simple task of deleting a handful of lines of configuration, you have no business being a server owner. Leaving negative reviews all over this developers work is petty.

Sincerely,
Server owner of 8 years.

**Comment by strahil211** [comment]
First of all sorry for not putting "popular" actually garbage plugins to get This one to work. I have Premium HeadsDatabase plugin not that cheap "Custom Heads" that AACH requires apparently. And MythicMobs is an absolute mess and does not work well in my particular server. All I'm saying is that I shouldn't have to immediately Delete config lines from a Premium plugin because of this... now That's Petty, but thanks for your unhelpful opinion. 

Sincerely,
Server owner for 9 years.

**Comment by PyvesB** [comment]
Thanks for clearing things up @TheCashFire , you're right on spot. 👍🏻 

Cc @xikage and @IHasName, your plugins were labelled as "garbage", "cheap" and an "absolute best". Thought it was worth giving you a heads up as the user strahil211 has a record of trashing projects behind maintainers' backs but then shamelessly asking them for assistance. You've been warned. 😉

**Comment by strahil211** [comment]
It was a valid feature request.
I'm not allowed to think a certain plugin is garbage? It's nothing personal lol
It's fine, don't improve your plugin. 
I'm sure you think it's amazing but its really not worth the money.
