### ISSUE TITLE
Before Buying plugin:

### ISSUE THREAD

**Issue by red0fireus** [PyvesB/advanced-achievements#918]
I'm quite confused on configuration for this plugin. I'm looking at the documentation and I don't see any categories list and playtime doesn't seem to want to run commands.

  '5':
    Goal: Play 5 hours.
    Message: You played for five hours on the server!
    Name: playedtime_5
    DisplayName: Fifth Hour
    Rewards:
      Command:
        Execute: give PLAYER minecraft:acacia_boat 10

**Comment by PyvesB** [comment]
@red0fireus I'm assuming you spotted the issue with your configuration? :)
