### ISSUE TITLE
something.

### ISSUE THREAD

**Issue by Remski01** [PyvesB/advanced-achievements#919]
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 
* Spigot username: Remski

:clipboard: **Description**

Add an option to let blocks placed by players dont count towrds achievments, only naturally generated ones. Such as, placing iron ore and removing then and repeat.

**Comment by PyvesB** [comment]
Please fill in the issue template and write a sensible title - this really feels like "I don't care". 😉 

As far as I know, there is nothing in the Bukkit/Spigot API that tells you whether a broken block was generated naturally or not. Even if there was, users could always build some sort of redstone machine to generate or move blocks, consequently tricking the plugin. I don't think this can be done.

**Comment by Remski01** [comment]
Hello.

The plugin McMMO does is. So there should be an easy to be enable to do this. So i will Nossr how he does it.

**Comment by PyvesB** [comment]
Well, I would be curious to know McMMO does it, so let me know. However, I suspect it's not easy as you're suggesting, I've got a feeling it must store all information in some sort of database. If that's the case, it's a lot of complexity and would come at a performance cost.

**Comment by Remski01** [comment]
> come at a performance cost

I dont agree with that aspect. No offens, but McMMO does so much more then AdvancedAchievments and we never had any issue with peformance, nor does anybody else as far we noticed from the not existing peformance issue reports on the discord. 

But yes, going ask Nossr how he have done that. What i have noticed is that there is an folder for mcmmo regions what does take a very little more space.

https://postimg.cc/jwzdRmVF

https://postimg.cc/5jbF6qPC

**Comment by Remski01** [comment]
Somone from there discord responded, the reason for the files are bellow, i asked if he could point to the code that does this.

The way mcMMO tracks this is via region files.
<see pics>

[17:38]
mcMMO creates a region file whenever a player interacts with the world in some manner related mcMMO. Such as mining an ore, or placing an ore.(edited)

[17:39]
These files are updated/edited as things within that region are changed.

[17:40]
If you block these files from being created, or from being read, then a player can infinitely gather things and levels just by placing blocks down and breaking them again.

**Comment by Remski01** [comment]
As far now you could take a peak at the code of McMMO as its open source https://github.com/mcMMO-Dev/mcMMO as its posibble and really neat/nice to have to prevent people placing and remove the blocks to extremly fast get the achievments.

Would be willing to donate if you could add this as i think that is something what is very usefull in a ton of situations.

**Comment by PyvesB** [comment]
Rather than reproducing similar code in Advanced Achievements, do you know if mcMMO plans on making it available through an API? It would be much easier to integrate with existing functionality rather than duplicating region data and reinventing the wheel.

**Comment by Remski01** [comment]
Nossr said:

his simplest way to do what he wants is to make use of Spigots NBT API stuff (PersistentDataContainer etc) 

was also asked to ask you if you could take a look here, its about the region stuff so you could look how mcmmo does it.

https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/java/com/gmail/nossr50/util/blockmeta

**Comment by PyvesB** [comment]
Okay, thanks for the info! Possibly something I'll look at sometime in 2021 :)
