### ISSUE TITLE
Randomly High Tick Usage

### ISSUE THREAD

**Issue by strahil211** [PyvesB/advanced-achievements#920]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.4
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes

:beetle: **Description**

Random high tick usage from the plugin dropping 2 to 3 ticks on a server that's running on an R9 3950x and 20gb ram

:page_facing_up: **Server logs**

````
![aach](https://user-images.githubusercontent.com/69178324/103184358-6eaee680-487d-11eb-8e0c-7663720a0c16.JPG)

````

:wrench: **Configuration**

Default configuration

````

**Comment by strahil211** [comment]
![timings](https://user-images.githubusercontent.com/69178324/103184440-ec72f200-487d-11eb-8f1a-b02bfd1a57d5.JPG)

Timings over an hour, 13 players

**Comment by strahil211** [comment]
Seems to be only when players are using the plugin, on standby it doesn't use any tick. Any ideas?

**Comment by PyvesB** [comment]
If you want to get help again on this project, I first expect a radical change in attitude towards users, myself and other developers, both on github.com and spigot.org. Insultive or obnoxious remarks, defamatory statements, lack of basic courtesy, repeatedly getting into arguments with people, are not things that will be tolerated on this open-source project.

**Comment by strahil211** [comment]
Still not sure why you'd refuse to help, as others may have a similar issue. It's not about me or you as a person it's about the resource and improving it for everybody. But That's alright I'll be sure to mention it in my next review
