### ISSUE TITLE
Place Blocks

### ISSUE THREAD

**Issue by calicogaming** [PyvesB/advanced-achievements#922]
Is there anyway to have an Achievement of Placing a number of Total Blocks? (Regardless of block type). For example:
“Congratulations! You placed 5000 Total Blocks”
If so, I assume you can do it with block breaks and mob killing aswell. Thank you and let me know!

**Comment by PyvesB** [comment]
Hello @calicogaming! 👋🏻 

Counting the total number of places isn't currently possible, see #824 and other similar issues.
