### ISSUE TITLE
Help with an Achievement setup.

### ISSUE THREAD

**Issue by SirCraftypants** [PyvesB/advanced-achievements#923]
Kills:
  sheep|cow|rabbit|chicken|pig:
    '100':
      Goal: Kill 100 Animals.
      Message: Your first Hunt!
      Name: kills_100_any            <-------how do i set this properly
      DisplayName: Hunter!

**Comment by PyvesB** [comment]
Hello @SirCraftypants ! 👋🏻 

The `Name` is mainly used as the key in the database, you can give it any value you want as long as you don't change it. :wink:

**Comment by SirCraftypants** [comment]
> 
> 
> Hello @SirCraftypants ! 👋🏻
> 
> The `Name` is mainly used as the key in the database, you can give it any value you want as long as you don't change it. 😉

Makes no sense to me? you can change it but you can't change it?

**Comment by SirCraftypants** [comment]
Example:

Places:      
  acacia_planks|birch_planks|dark_oak_planks|jungle_planks|oak_planks|spruce_planks:
    '500':
      Goal: Place 500 Planks.
      Message: §6You have placed 500 Planks!
      Name: place_500_planks
      DisplayName: Plank Layer 
      Reward:
        Experience: 100      
      Command:
        Execute: lp user PLAYER permission set jobs.join.Builder true    
        Display: Unlock Job Builder


https://paste.helpch.at/loyucawixa.bash

**Comment by PyvesB** [comment]
> Makes no sense to me? you can change it but you can't change it?

Well, pick it once when you first create the achievement, but don't change it again.

**Comment by SirCraftypants** [comment]
I did with the example above but in the link above it what happened.

**Comment by SirCraftypants** [comment]
As you can see it's name parameter is there but it's saying it's missing.

**Comment by PyvesB** [comment]
The indentation of the configuration may be incorrect. Could you please share the config in a code block or on pastebin.com?

**Comment by SirCraftypants** [comment]
https://paste.helpch.at/cojehequve.coffeescript

**Comment by PyvesB** [comment]
Many `Command` sections are not properly indented. They need to be within a `Reward` section. For example, that's the case on line 514 in the configuration you shared.

**Comment by SirCraftypants** [comment]
> 
> 
> Many `Command` sections are not properly indented. They need to be within a `Reward` section. For example, that's the case on line 514 in the configuration you shared.

thank you

**Comment by PyvesB** [comment]
You're welcome! I also noticed that you used `Commands` in one place instead of `Command` (no plural!).

**Comment by SirCraftypants** [comment]
> 
> 
> You're welcome! I also noticed that you used `Commands` in one place instead of `Command` (no plural!).

Yes i just noticed that is in the statistics command, I've corrected that now thanks but thats as default in your config, i didn't create that command.

**Comment by PyvesB** [comment]
> > You're welcome! I also noticed that you used `Commands` in one place instead of `Command` (no plural!).
> 
> Yes i just noticed that is in the statistics command, I've corrected that now thanks but thats as default in your config, i didn't create that command.

You're right, good spot! If you want, you can submit a fix by pressing the edit button on the default config [here](https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml), otherwise I'll fix it myself later. :wink:
