### ISSUE TITLE
Trying to build project.

### ISSUE THREAD

**Issue by jordanwilliams1** [PyvesB/advanced-achievements#924]
Hey, When I'm trying to build org.h2.message.DbException: Error while creating file

https://pastebin.com/raw/jLedWtSW

**Comment by PyvesB** [comment]
Hello @jordanwilliams1 ! 👋🏻 

Building works locally in a terminal and in Eclipse, GitHub's CI seems happy as well. Not sure what IntelliJ is up to here, can you reproduce in a standalone terminal?

**Comment by HeyItsRed** [comment]
@PyvesB Compiled fine on my copy of IntelliJ, I've messaged Jordan on discord and notified its an issue most likely with his IntelliJ and not the resource itself.

**Comment by PyvesB** [comment]
> @PyvesB Compiled fine on my copy of IntelliJ, I've messaged Jordan on discord and notified its an issue most likely with his IntelliJ and not the resource itself.

Great, will close then! 👍🏻
