### ISSUE TITLE
Subcategory display block

### ISSUE THREAD

**Issue by MehanoPT** [PyvesB/advanced-achievements#925]
Hello,
I have some achievements on my server like visit X world Y times.
As i didn't find any category that suits that task i am using the custom category and adding when a player visit the world.
It works, but now i want a thing.
Is it possible to change the display block for each achievement on advancement tab menu? (/aach generate)
It looks kinda ugly this way.

![image](https://user-images.githubusercontent.com/4977257/103443627-1e5ace80-4c59-11eb-95eb-4381ea1fa047.png)

Thanks

**Comment by PyvesB** [comment]
Hello @MehanoPT ! 👋🏻 

Unfortunately, it's not currently possible to change the icons in the advancement GUI on a per-subcategory basis. The Bukkit/Spigot API to manage vanilla advancements is impractical - they've labelled it as 'unsafe' and 'deprecated', so I don't think this will be added to the plugin at this point in time.

However, underneath the hood, a JSON file is generated on the server for each advancement. You can easily open them up and modify the icon data value in them. 😉

**Comment by MehanoPT** [comment]
Thank you @PybesB
I'm don't play neither configure any server for 3 years and i'm getting used to it again.
Thanks for the info.
I've done a script that whenever i do /aach generate it will get the info from a yml i have and put it in the individual advancement json, then run /minecraft:reload
It works 😃 
![image](https://user-images.githubusercontent.com/4977257/103445609-7819c380-4c6e-11eb-81de-a0d93bcbeb87.png)
Cheers

**Comment by PyvesB** [comment]
Sounds great! 👍🏻 

I myself haven't played the game on a proper server since ~mid-2017. Luckily though, that doesn't matter much when it comes to plugin development :)

Anyway, happy new year!
