### ISSUE TITLE
'Back to Achievements List' Button having a configurable command line/string run when clicked

### ISSUE THREAD

**Issue by TheCashFire** [PyvesB/advanced-achievements#926]
:information_source: Regarding the GUI for AdvancedAchievements, just a helpful little line that would allow us to build our own GUI's.

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username: TheCashFire

:clipboard: Description
Adding a small subnode for the 'Back to Achievements List' button in the GUI, allowing us to give a command to be executed when that button is pressed and the user returns to the main menu. Would help immensely with custom GUI creation, as right now, a user can go in and see their achievements through a custom GUI but has to close the menu to reopen any external GUI. Just a small QOL. Thanks!

I don't have anyone to make a pull request.

**Comment by PyvesB** [comment]
Hello @TheCashFire ! 👋🏻 

Hmmm, I'm not sure a subnode would be the best solution, maybe a separate `OverrideBackButtonBehaviour` option in _config.yml_ would be clearer. I'll have a think on the best way to design this.

I'm assuming `PLAYER` would be the main placeholder in the command?

**Comment by TheCashFire** [comment]
Ideally, yes, they player that clicked on it would be the target. I can’t imagine that would need configuring as there wouldn’t logically be another target than the user operating the GUI. It would just allow for switching between menus without having to close it and reenter a new command. Thanks!

**Comment by PyvesB** [comment]
Implemented! 🍾

**Comment by PyvesB** [comment]
@TheCashFire  by the way, would you be interested in beta testing the next version of the plugin?

**Comment by TheCashFire** [comment]
Sure! Looking forward to it.

**Comment by PyvesB** [comment]
Check out this comment then: https://github.com/PyvesB/advanced-achievements/issues/741#issuecomment-772019652 :)
