### ISSUE TITLE
Migrating from h2 to mysql, I can not find any information on this.

### ISSUE THREAD

**Issue by Esronn** [PyvesB/advanced-achievements#927]
Hello,

How do I migrate from h2 to mysql without losing player progress?

**Comment by PyvesB** [comment]
Hello @Esronn ! 👋🏻 

To be honest, I don't know as it's not something I've ever done myself and I've not heard of any user of the plugin do it over the years either.

However, I did find the following links by performing a quick search on the Internet:
https://stackoverflow.com/a/30477208/3527464
https://github.com/pedromartins4/H2-to-MySQL
https://github.com/dbeaver/dbeaver/wiki/Data-migration

Hope this helps!
