### ISSUE TITLE
How to configure mysql database?

### ISSUE THREAD

**Issue by luisdavidsj** [PyvesB/advanced-achievements#930]
I want to know how to configure a mysql database and connect the plugin to a table. I have a server and the possibility to create db's. I just want to know how-to config the database.

**Comment by PyvesB** [comment]
Hello @luisdavidsj ! 👋🏻 

Create a new MySQL database, for example call it `minecraft`. Then specify `mysql` in the plugin's configuration [here](https://github.com/PyvesB/advanced-achievements/blob/33669bdffe35cc4f4df03409980d75486ab7abb7/advanced-achievements-plugin/src/main/resources/config.yml#L222) and fill in the `DatabaseAddress`, `DatabaseUser` and `DatabasePassword` parameters. 😉 

Hope this helps!
