### ISSUE TITLE
GitHub Actions artifact build

### ISSUE THREAD

**Issue by Baterka** [PyvesB/advanced-achievements#931]
Can you please add jar artifact building in GitHub Actions?

**Comment by PyvesB** [comment]
Hello @Baterka! 👋🏻 

This probably won't be added. Individual commits are often not properly tested on a server and sometimes contain work in progress. The resulting jars may mess things up on servers or simply not work. Users have been quite happy with the release cycle over the years, so I will keep on providing jars when new versions are polished, tested and finalised.
