### ISSUE TITLE
Item Lore for Rewards

### ISSUE THREAD

**Issue by calicogaming** [PyvesB/advanced-achievements#934]
When a player gets an achievement award and it is an Item, I figured out how to edit the name of the item but can you make a lore? Thanks!

**Comment by PyvesB** [comment]
Hello @calicogaming ! 👋🏻 

If you want to further customise the item rewards, use a command reward instead, similarly to what is explained here: https://github.com/PyvesB/advanced-achievements/issues/556#issuecomment-511111096
