### ISSUE TITLE
Splited advancements paths

### ISSUE THREAD

**Issue by charlesthms** [PyvesB/advanced-achievements#939]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.4/5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: YES
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: YES

:question: **Help request**

Hello !
After reading and searching the best I can I didn't find any way to split the path of the vanilla advancement tab. Also to choose the icon for each advancement.
So firstly is it possible ? And if no will it be added in future update ?
Here is an illustration of what I'm thinking of:

![image](https://user-images.githubusercontent.com/65021094/105576627-5cd53c00-5d74-11eb-9d1e-e14f41028283.png)

Thank you in advance.

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @charlesthms! 👋🏻 

I suggest reason through  #936 and #925, they will hopefully help you out. 😉

**Comment by charlesthms** [comment]
Thank you that's what I was looking for !

**Comment by PyvesB** [comment]
No worries!
