### ISSUE TITLE
[7.0.0 beta] Database connection

### ISSUE THREAD

**Issue by aurel85** [PyvesB/advanced-achievements#943]
Hi,

AdvancedAchievement is disabled in 1.16.5 (Paper) with database : https://pastebin.com/5Heqe60g

**Comment by aurel85** [comment]
ok I understood, with the update it adds new lines to enter the address of the database knowing that it is already entered higher, that's why I did not understand everything following why there was this concern.

**Comment by PyvesB** [comment]
Just to confirm, was your database section previously looking like the following?
```
MYSQL:
  Address: ...
```

The style was changed to `DatabaseAddress` and similarly named parameters all the way back in November 2018, but until 7.0.0, backwards compatibility was still kept. :)

**Comment by aurel85** [comment]
that's it all right, for this version it is perhaps advisable to reset the config?

**Comment by PyvesB** [comment]
> it is perhaps advisable to reset the config

I would tend to say no. I thing it's the only breaking change alongside the `list-potions` one in _lang.yml_. If I clearly mention both in the final changelog, it should hopefully be fine. :)
