### ISSUE TITLE
Advancement by aquiring item w/ specified durability

### ISSUE THREAD

**Issue by mrboog12** [PyvesB/advanced-achievements#944]
Is it possible to, with this to create an advancement that if [Example] I get a diamond sword with 134 durability, it triggers an achievement?

**Comment by PyvesB** [comment]
Hello @mrboog12! 👋🏻 

There is currently no way to directly award an achievement when a player completes a specific Vanilla advancement. The _AdvancementsCompleted_ category simply keeps track of the number of advancements received. You could however setup a _Commands_ achievement, and then run an _aach give_ command function as part of the reward for the completion of the matching advancement. 😉
