### ISSUE TITLE
Bungee mode 

### ISSUE THREAD

**Issue by Z3dC0d3** [PyvesB/advanced-achievements#945]
:information_source: **Hello how I setup the plugin on bungee mode ?**

* Advanced Achievements version: 6.7.2
* Minecraft version: 1.8-1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes, am not found nothing about bungee mode
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 

:question: **Help request**

I want to make that plugin on multiply server with different achivments, but have some features like kills

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @Z3dC0d3! 👋🏻 

Frankly, I'm quite confused. If, as you said, you want different achievements on different servers, then you actually don't want any BungeeCord integration. However, if in reality you want the same statistics and achievements shared on different servers, then you can simply use a PostgreSQL or MySQL database and simply set the `BungeeMode` parameter to true in the database. 😉 

Hope this helps!
