### ISSUE TITLE
Dont count the same item over and over

### ISSUE THREAD

**Issue by rosiejane** [PyvesB/advanced-achievements#946]
Hello everyone.

As far as i know, this has been like this since the plugin was made. But is there any way to stop the "Blocks Placed" category for example, from counting the same block over and over.

 Lets say i have an achievement saying "place 10 oak saplings" Players can get this achievement by placing down 1 sapling, picking it up again and placing it down again over and over.

Another example "Blocks Broken"
 Lets say i have an achievement saying "mine 100 diorite" Players can again get this achievement from just 1 single block. Simply place it down and mine it. Place it down and mine it over and over 10 times.

I would love for the plugin not to count player placed items.

I'm pretty sure i did speak to @PyvesB about a similar issue 2 years ago or more and he had it on his feature list. But i simply cannot find the conversation anywhere.

Thank you

**Comment by PyvesB** [comment]
Hello @rosiejane ! 👋🏻 

> I'm pretty sure i did speak to @PyvesB about a similar issue 2 years ago or more and he had it on his feature list. But i simply cannot find the conversation anywhere.

I have no recollection of this happening and indeed GitHub indicates that the only other issues that you've opened over the years are #851 and #567, both of which are unrelated. I'm also unsure what you mean by "feature list" given that I've personally never maintained such a list for this project. You're possibly confusing things with a different project and author.

Anyway, if your question is "can Advanced Achievements not count items placed by players?", the answer is "currently no" as indicated in duplicate #919. 😉

**Comment by rosiejane** [comment]
> 
> 
> Hello @rosiejane ! 👋🏻
> 
> > I'm pretty sure i did speak to @PyvesB about a similar issue 2 years ago or more and he had it on his feature list. But i simply cannot find the conversation anywhere.
> 
> I have no recollection of this happening and indeed GitHub indicates that the only other issues that you've opened over the years are #851 and #567, both of which are unrelated. I'm also unsure what you mean by "feature list" given that I've personally never maintained such a list for this project. You're possibly confusing things with a different project and author.
> 
> Anyway, if your question is "can Advanced Achievements not count items placed by players?", the answer is "currently no" as indicated in duplicate #919. 😉

Thank you for the reply. 

By "feature list" i mean a possible feature that might be added in a future update.

> 
> 
> Okay, thanks for the info! Possibly something I'll look at sometime in 2021 :)
I look forward to it :)

One last question though Pyves. Can we make it so the "/aach list" GUI can display hex color codes?

![image](https://user-images.githubusercontent.com/54243352/107153702-cce3e480-6966-11eb-91ae-b2ea7d475ea5.png)


Thank you

**Comment by PyvesB** [comment]
> Can we make it so the "/aach list" GUI can display hex color codes?

Advanced Achievements simply calls `player.sendMessage` with the `Display` string you shared. If hex colours are not being displayed correctly, I would be tempted to say it's not supported by Minecraft or there's a bug/missing feature in the Spigot API.

**Comment by rosiejane** [comment]
> 
> 
> > Can we make it so the "/aach list" GUI can display hex color codes?
> 
> Advanced Achievements simply calls `player.sendMessage` with the `Display` string you shared. If hex colours are not being displayed correctly, I would be tempted to say it's not supported by Minecraft or there's a bug/missing feature in the Spigot API.

Yes i didnt see this reply sorry!

Do you think this will be possible in the future then or not. Thank you

**Comment by PyvesB** [comment]
Dunno for sure. Someone would need to dig into the Spigot API and raise feature requests/bug reports with them if necessary.
