### ISSUE TITLE
Web based interface to create new achievements

### ISSUE THREAD

**Issue by Kissadere** [PyvesB/advanced-achievements#947]
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username: Kosscielsky

:clipboard: **Description**

I'm developing a web based system for Advanced Achievements. This system will help users create new achievements, faster and easy; without touching code, using their web browser and filling out the necessary information from a form.

It's still a work in progress, i've tested it myself and so far, works like a charm. 
Due to my programming limitations, i had to create different files for every achievement type, this means; you'll have to copy and paste their output to the original plugin's config file, in order to make it work.

**Repository:** https://github.com/Kissadere/AdvancedAchievements-Web-Gui

Please, fell free to contribute the project, i think it's a great idea for the plugin :)

**Comment by PyvesB** [comment]
Hello @Kissadere ! 👋🏻 

Haven't yet had a chance to try things out, but it sounds promising. Thanks for sharing! 👍🏻 

Two thoughts come to mind:
* could the UI be statically hosted via GitHub pages for example? Here's a example of a small website for one of my other projects: https://pyvesb.github.io/eclipse-solargraph
* would it be possible for users to paste their current config in the UI, which would then simply be modified in place when new achievements are added?

**Comment by Kissadere** [comment]
Hello there!

Thanks for taking time to look up on this.

- I have a hosted version of the site/system on my personal website, you can find it here: https://zibuu.net/achievements
- About importing current settings, i'm not sure how to make PHP to read/handle YAML files but i'll google it and try make it possible for next updates.

**Comment by PyvesB** [comment]
As a side note, I think that @supertassu and @Rsl1122 (both have contributed to this project in the past) have a little more experience in frontend development than I do, so they might be able to offer some guidance as well. ;)

**Comment by Kissadere** [comment]
Thanks!

Today i made an update, adding multi-language support (English and Spanish) and a section to configure the system to fit your needs, such as changing the language, website title and limitations of how much money to reward per achievement.

I also added a default translation for English and improved some other stuffs.
I'm still working on importing the plugins config file, it'll probably be ready for V3.0.0

**Comment by AuroraLS3** [comment]
Hi (Rsl1122 with a new username here)

I don't unfortunately know PHP to offer any guidance :(

If you don't want to write a custom style sheet for your app you can use a framework like [Bootstrap](https://getbootstrap.com/) (It's a pretty good framework to get started with styling.) Another alternative is Google's Material design https://material.io

**Comment by PyvesB** [comment]
>     * I have a hosted version of the site/system on my personal website, you can find it here: https://zibuu.net/achievements

The page doesn't seem to load, is that expected?

**Comment by Kissadere** [comment]
Oh, right! I forgot to tell you, I changed the URL to another domain: http://kssadere.online/

**Comment by TomLewis** [comment]
Could we get some screenshots? The hosted version just shows a white page.

Im glad you picked PHP to self host.

**Comment by Kissadere** [comment]
@TomLewis Are you sure you're typing the right website? 
You can check out the project here: http://kssadere.online
Output data is available here: http://kssadere.online/builder/content/

**Comment by Kissadere** [comment]
Hi, as of now (and this week) I have been migrating my hosting providers to my dedicated servers, plus setting up some other stuffs there, that's why some of my domains are down right now, i'm very sorry for it.

It'll be back as soon as i finish all the setting up process over here.

**Comment by Kissadere** [comment]
The web interface is back online.

This is the new url: https://achievements.zibuu.net/

Also, i've translated the messages from the plugin to Spanish, since the original Spanish translation was kinda "robotic".
It's available here: https://pastebin.com/4DwbU2w5

**Comment by TomLewis** [comment]
How do I set it to English so I can read it?

**Comment by PyvesB** [comment]
> How do I set it to English so I can read it?

Probably best to report directly to https://github.com/Kissadere/AdvancedAchievements-Web-Gui

Will close this issue for the time being. 😉
