### ISSUE TITLE
Villager trade category update needed

### ISSUE THREAD

**Issue by rosiejane** [PyvesB/advanced-achievements#949]
Hello Everyone @PyvesB 

I hope the villager trade category can be updated. I'll try and explain the best i can.

So any of these trades shown in the below image, will take your trade /aach up by 1, each time you trade the villager
![image](https://user-images.githubusercontent.com/54243352/107714511-59730780-6cc5-11eb-8eac-228c08b8743c.png)

But if you use the types of trades that gives the player more than 1 item, for example here. 1 emerald = 4 glass. The glass will make your /aach go up by 4! even though you only traded once with the villager.
![image](https://user-images.githubusercontent.com/54243352/107714695-9f2fd000-6cc5-11eb-89b9-e9b25389bf5d.png)

It turns out some players have been using this technique to unlock my trading achievements really quickly which seems cheating.
Take a look at this. the /aach goes up by 16 every time you trade the villager which i dont think is right. 1 trade should be 1 /aach. not 16!
![image](https://user-images.githubusercontent.com/54243352/107714954-23825300-6cc6-11eb-850e-ade11ba4ca69.png)

Thank you

**Comment by PyvesB** [comment]
Hello @rosiejane ! 👋🏻 

Yes, I think that makes sense, thank for reporting. Fixed in aforementioned commit. 😉
