### ISSUE TITLE
Support the built in achievements by pressing L.

### ISSUE THREAD

**Issue by TomLewis** [PyvesB/advanced-achievements#953]
Minecraft has a built in achievements system, this should be the system that achievements are listed.
There is an API already to help developers do this https://www.spigotmc.org/resources/crazy-advancements-api.51741/

Please use this.

**Comment by PyvesB** [comment]
Hello @TomLewis ! 👋🏻 

The Vanilla achievement system was removed in Minecraft 1.12 and is no longer available since 2017. Whilst Advanced Achievements is still compatible with old Minecraft 1.7-1.11 versions and I try to backport new plugin features wherever possible, I don't intend on implementing features exclusive to legacy versions. 😉

**Comment by TomLewis** [comment]
Aha nuts! yeah I'm playing using 1.12.2! I had no idea they replaced it with "Advancements". Yeah I must have miss-read that plugin, thats called Crazy Advancements, not achievements. 

I opened 1.16.5 and pressed L, the window still exists. 
Maybe add "Advancements" support then! Wrong wording!

Funny, I am still using 1.12.2 for my server tho! So I couldn't use it! (yet)

**Comment by PyvesB** [comment]
Ah, so Vanilla _advancements_ is a different story. They are supported by the plugin, there's an _/aach generate_ command documented [here](https://github.com/PyvesB/advanced-achievements/wiki/Commands). There's also an _AdvancementsCompleted_ achievement category that provides another level of integration with Vanilla advancements. :)

**Comment by TomLewis** [comment]
Oh snap you already have this? It looks like 1.12.2 uses advancements too, as there's a tab on the top! So this should work on my paper 1.12.2?

**Comment by PyvesB** [comment]
Yes, it should work.
