### ISSUE TITLE
Book cooldown resetting

### ISSUE THREAD

**Issue by Klotzlutscher** [PyvesB/advanced-achievements#954]
* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.4
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
:beetle: **Description**

Hi ,
we have a problem with the Aach Book Coldown.
We use 6 Servers in a bungeemode, if i go on Server A get the Book with /aach book then i get the Cooldown that we set in Config. If i go on Server B the Cooldown is been resetet and i can get the Book again. If i go back to Server A i can get the book againg too then.We had for all the same Database.Bungeemode is enabled. The config are all the Same.

If you need more detailed information i can bring it, just say what you need.

greets Klotzlutscher

**Comment by PyvesB** [comment]
Hello @Klotzlutscher ! 👋🏻 

Thanks for pointing this out. This has pretty much been the case since the plugin was created. As it's quite minor, I'm guessing no one went through the effort of reporting it or fixing it. May look at it in a future update. 😉

**Comment by Klotzlutscher** [comment]
Hey @PyvesB ,
Today we had figured out that is not only the Book that is cooldown reseting. Its for all Stuff that had Cooldown.
examples: Listening to Disc or Sleep in a Bed.
Our Dev asked about if its possible to Speak over Discord with you , he had a few things who he want to talk about.Improvements something about a API etc. He can bether describe what he means , iam only the Admin that makes the Config :D 

Greets Klotzlutscher

**Comment by PyvesB** [comment]
> Today we had figured out that is not only the Book that is cooldown reseting. Its for all Stuff that had Cooldown.

Yep, I'm aware, anything that is of type "Cleanable" in the code base needs to be reworked a little.

> Our Dev asked about if its possible to Speak over Discord with you , he had a few things who he want to talk about.Improvements something about a API etc.

If he's a developer, surely he must be well versed in using a platform such as GitHub. Especially if it's things relating to the API, this is by far the best place to discuss them. 😉

**Comment by Klotzlutscher** [comment]
Thanks a lot for fixing the cooldown problem.
I have tested it now but there is still a little problem.

Server: MC: 1.16.5 Paper-547
AACH Version: 7.0.1

Is it possible to store the cooldown in a Databasetable?
We are using a Bungeecord Network with several Servers and if a Player is switching between the Servers he will get on each Server a seperat Cooldown for the Book, e.g. and this happens also after a Server restart.
