### ISSUE TITLE
RGB Colors

### ISSUE THREAD

**Issue by rosiejane** [PyvesB/advanced-achievements#958]
Hello. @PyvesB 

Please can we have the ability for RGB Colors to show up in the "/aach list" GUI please under "rewards"

![image](https://user-images.githubusercontent.com/54243352/108769569-129cd180-7551-11eb-9b0f-e89fc24669eb.png)

![image](https://user-images.githubusercontent.com/54243352/108769675-3829db00-7551-11eb-956c-700912566086.png)

Thank you

**Comment by PyvesB** [comment]
Hello @rosiejane ! 👋🏻 

You may have missed my answer here: https://github.com/PyvesB/advanced-achievements/issues/946#issuecomment-778607627
