### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#959]
:information_source: **Basic information**

* Advanced Achievements version: 6.2.1
* Minecraft version: paper 1.16.4 B396
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: YES
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: YES

:question:
How in the world do you change the color for certain aspects?
<img width="162" alt="Screenshot 2021-02-22 181929" src="https://user-images.githubusercontent.com/25316276/108787375-39500d80-753b-11eb-870c-99be464356c2.png">
<img width="110" alt="Screenshot 2021-02-22 181941" src="https://user-images.githubusercontent.com/25316276/108787397-43720c00-753b-11eb-935c-10e403875483.png">

I'm trying to change the color of the date and the single dot. Also, how do you change the dot icon to something else? I've searched through both the config and the lang.yml and haven't found any UTF-8 code besides the check mark

:wrench: **Configuration**

Not sure if posting the config is relevant to the issue since the thing I want to change would be already default. 
And the default color is 'b'
```
# Set the color of the plugin (default: 5, dark purple).
Color: b
````

I thought I remember someone else reporting something similar and I was right, but it was regarding v6.2.0 here #839
Was this issue solved in a later version past 6.2.1?

**Comment by PyvesB** [comment]
Hello @BobbyMere ! 👋🏻 

Yes, as indicated in that duplicate issue, this was solved. You'll need to update to version 6.7.0 of the plugin or more more recent. 😉
