### ISSUE TITLE
Jobs Reborn Hook Not Working

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#960]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.4 paper
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: YES
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: YES

:beetle: **Description**

The new Jobs Reborn hook doesn't seem to work. I tested this with jobs reborn v4.17.0 with AA v6.7.2 and placed the default 
```
JobsReborn:
  hunter:
    1:
      Goal: Level up as a hunter!
      Message: You have reached hunter level 2!
      Name: jobsreborn_1_hunter
      DisplayName: Hunter
      Type: normal
```
Joined the Hunter job and did /jobs promote ergenta hunter 3 and no achievement was made. It still shows in the gui that I haven't reached lvl 2 even though with /jobs stats it shows my hunter is level 3. This was with both default jobs and AA.

 
:page_facing_up: **Server logs**

There's no errors

:wrench: **Configuration**

```
JobsReborn:
  hunter:
    1:
      Goal: Level up as a hunter!
      Message: You have reached hunter level 2!
      Name: jobsreborn_1_hunter
      DisplayName: Hunter
      Type: normal
```
would you happen to know what the issue is? I also made sure it wasn't in the disabled section
<img width="418" alt="Screenshot 2021-02-23 175300" src="https://user-images.githubusercontent.com/25316276/108924330-10458080-7600-11eb-8412-b243784aa114.png">
<img width="418" alt="Screenshot 2021-02-23 175255" src="https://user-images.githubusercontent.com/25316276/108924349-16d3f800-7600-11eb-9e2a-4d51768848ec.png">
<img width="350" alt="Screenshot 2021-02-23 175249" src="https://user-images.githubusercontent.com/25316276/108924354-1a677f00-7600-11eb-8b5d-cd9af08b90f2.png">

Also 
```
AdvancementsCompleted:
  '1':
    Goal: b
    Message: b
    Name: AdvancementsCompleted_1
    DisplayName: b
    Type: normal
```
Doesn't work either it seems. I made sure to remove it from the disabled list as well
[config.zip](https://github.com/PyvesB/advanced-achievements/files/6032608/config.zip)
https://mcpaste.io/28e4cb0566297a9d

**Comment by PyvesB** [comment]
As far as I remember _/jobs promote_ does not trigger `JobsLevelUpEvents`, you need to increase your job level "manually". This may be an issue to raise with the JobsReborn team. 😉

**Comment by BobbyMere** [comment]
I realized this a couple hours after I made the ticket
