### ISSUE TITLE
Placeholder Support In Gui

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#961]
Description of request:
I was wondering if you could add placeholder support within the Gui title so we can put how many in total achivements there are and how many the individual has.
<img width="329" alt="Screenshot 2021-02-23 212923" src="https://user-images.githubusercontent.com/25316276/108943575-bb653280-761e-11eb-9458-6c3726cba173.png">

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: YES
* Spigot username: Ergenta

I don't know anyone who is willing to do pull requests

**Comment by PyvesB** [comment]
Hello @BobbyMere ! 👋🏻 

It looks a bit odd to have the numbers in the title. Probably best to not overload the GUI with information that is readily available in other commands such as _/aach stats_. 

Counter proposal though: what do you think about having the number of achievements received by players when hovering over the individual categories? Where is says "3 achievements" for example, change that to be "2/3 achievements".

**Comment by BobbyMere** [comment]
That's interesting but you can just look at the achievements since unlocked and locked have different blocks indicating it. The reason I asked for it in the title is because no matter how many times I plaster /aach stats everywhere, people still don't know about the command so this would make it a lot easier.

**Comment by PyvesB** [comment]
> no matter how many times I plaster /aach stats everywhere

Well they can easily find the command in the help, so it's possibly worth plastering the top level `/aach` everywhere instead.

Alternatively, if you use a plugin such as BungeeTabListPlus, you can put the number of achievements for each player there, that's what I used to do back in the day when I managed my own server. You've also got the `aach_achievements` and `aach_total_achievements` placeholders from PlaceHolderAPI, so you can include them pretty much anywhere.

These all seem like better options that overloading `/aach list` with yet more information that is already found elsewhere. 😉
