### ISSUE TITLE
AdvancedAchievement Tracker

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#962]
* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.4
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes

Question:

I was wondering if there's a way to have a section for how many AA achievements you've obtained like how advancements are tracked. Basically Achievements for how many Achivements you've unlocked. If not, can it be added?

**Comment by PyvesB** [comment]
Hello @BobbyMere ! 👋🏻 

Yes, this can be done quite easily. See what @TheCashFire has done in  #914 for example. 😉

**Comment by BobbyMere** [comment]
I have to disable advancements for Achievements to be tracked?

**Comment by PyvesB** [comment]
If you want to track just advancements based on achievements from Advanced Achievements, you should disable Vanilla advancements in the server configuration. If you want to track a mixture of both, keep the default server configuration.
