### ISSUE TITLE
Catégories buggés 7.0

### ISSUE THREAD

**Issue by Teyir** [PyvesB/advanced-achievements#963]
Hey,

j'ai quelques soucis depuis la dernière version

![image](https://user-images.githubusercontent.com/60007549/109392398-1c8d4e80-791c-11eb-9000-eb4012efa185.png)

Voici un exemple de menu après la 7.0, alors qu'avant tout fonctionnait

De plus certains achievements ne sont plus affichés ( les premiers)

![image](https://user-images.githubusercontent.com/60007549/109392427-46df0c00-791c-11eb-9b76-d0f21b8d3709.png)

Et je suis sous yatopia 1.16.5

**Comment by PyvesB** [comment]
Hello @Teyir! 👋🏻 

Est-ce qu'il serait possible de partager ta configuration ? J'ai pas l'impression qu'on puisse reproduire avec la config par défaut.

**Comment by Teyir** [comment]
Pas de soucis, voici ma config

https://pastebin.com/wfZ578Si

( J'ai bien enlevé mes id mysql ;) )

**Comment by PyvesB** [comment]
Amusant comme bug, n'est-ce pas ?

Voila, c'est corrigé. Soit tu désactives `NumberedItemsInList` jusqu’à la prochaine mise-à-jour, soit tu recompiles le plugin. 😉

**Comment by Teyir** [comment]
Un peux la flemme de le recompiler, mais je vais faire ça, encore merci
