### ISSUE TITLE
Update from 6.7.2 to 7.0.0

### ISSUE THREAD

**Issue by LucidAPs** [PyvesB/advanced-achievements#966]
So how can I update from 6.7.2 to 7.0.0 without players loosing their progress and achievements?

**Comment by PyvesB** [comment]
Hello @LucidAPs ! 👋🏻 

Yes, you can update and keep all progress and achievements. Simply go through the "Breaking Changes" section of the changelog and make sure you update your configurations if needed. 😉

**Comment by LucidAPs** [comment]
I read it and that's why I am here. 
![image](https://user-images.githubusercontent.com/42933023/109429663-95b4a080-7a05-11eb-867c-65b244fc5d1e.png)
So I make a copy of my database and then use a restore command or something like that? Or I just make a copy and then what?
Or maybe I misunderstood what it says? Do you mean that that I will need a backup only if I want to go to earlier versions for some reason otherwise I'll be fine?

**Comment by PyvesB** [comment]
> Do you mean that that I will need a backup only if I want to go to earlier versions for some reason otherwise I'll be fine?

Yes, pretty much :)

**Comment by LucidAPs** [comment]
Thank you.

**Comment by PyvesB** [comment]
You're welcome. I've slightly tweaked the wording of the changelog to prevent any confusion with other users.
