### ISSUE TITLE
Ignore command given achievements if already earned

### ISSUE THREAD

**Issue by irritatingness** [PyvesB/advanced-achievements#971]
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username: EhhChris

:clipboard: **Description**

In the aach give command for custom achievements, it'd be nice to have the achievement only be given if it is not already earned. This could optionally be added without breaking current functionality with an additional parameter (false for example to not give if already earned, default to true).

Neither myself nor someone I know will be creating a PR (sorry).

**Comment by irritatingness** [comment]
I'm an idiot and found the config option, missed it even after going through the config a ton.

**Comment by PyvesB** [comment]
@irritatingness it's okay, glad that you find the `MultiCommand` option eventually. 😉
