### ISSUE TITLE
Books only get to page 100

### ISSUE THREAD

**Issue by Klotzlutscher** [PyvesB/advanced-achievements#975]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2 
* Minecraft version:  1.16.4 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes 

:beetle: **Description**

We had found another Problem withe the Book:
https://i.imgur.com/MqcJVJN.png 
We have 340 Achievements but the Book only gets to Page 100 maybe it can a bit squeezed or so to get more Achievements on 1 page?Is there A way to fix it?

**Comment by PyvesB** [comment]
Hello @Klotzlutscher! 👋🏻 

The code to handle book pages hasn't changed in Advanced Achievements for years, so this may be a Spigot/Minecraft limitation. Could you please check whether you can reproduce with earlier versions of the game (i.e. 1.15, 1.14, etc.) and report on the most recent version that does allow to go above 100 pages?

**Comment by Klotzlutscher** [comment]
hey, we dont have earlyer versions on our server, i will see if i can get a lokal server and try it.

**Comment by PyvesB** [comment]
Any progress on your local attempts @Klotzlutscher ? :)

**Comment by Klotzlutscher** [comment]
Hey, didnt find a functional version yet still on it.

**Comment by Klotzlutscher** [comment]
just a quick update, sorry my time is very limited at the moment , no version found yet.

**Comment by PyvesB** [comment]
No worries, will keep open for the time being.

**Comment by PyvesB** [comment]
It's been over three months, I'm going to go ahead and close this. No one else has reported this in the meantime, so either it only impacts a minority of users or folks simply don't care enough. Probably not a good use of my time either way.

Feel free to reopen when you're able to provide additional information!
