### ISSUE TITLE
Turtles arent counted in Breeding 

### ISSUE THREAD

**Issue by Klotzlutscher** [PyvesB/advanced-achievements#976]
information_source: **Basic information**

* Advanced Achievements version:  6.7.2 
* Minecraft version:  1.16.4 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read:  Yes 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:  Yes 

:beetle: **Description**

We had found a problem in the Breeding category.
Turtle arent countet. Even if they are from spawn Egg or natural spawned.We have tryed it with Turtle eggs,spawn eggs spawn command and natural spawned turtles.
That is the Config https://i.imgur.com/XKXbOCi.png

**Comment by PyvesB** [comment]
Hello @Klotzlutscher ! 👋🏻 

Spigot does not issue a `EntityBreedEvent` for turtles, so Advanced Achievements has no way of telling that a specific player has performed a breeding action. There is an [open Spigot bug about this](EntityBreedEvent), feel free to upvote it and add a comment to it. 😉

**Comment by Klotzlutscher** [comment]
I upvote it, thanks for the link.
