### ISSUE TITLE
MMOCORE Regen

### ISSUE THREAD

**Issue by Deeps209** [PyvesB/advanced-achievements#978]
Hi! I use this plugin to keep track of how many item people have been colecting and at some milestones i award them. But i use the mmocore regen system wich seems to break this plugin and not count to the break achievements. Can you fix this issue or tell me what to do to make it work.

**Comment by PyvesB** [comment]
Hello @Deeps209! 👋🏻 

"Advanced Achievements stops working when plugin X is added" is most likely not a bug with Advanced Achievements. The classic example is AutoSell which violates the Bukkit API (see #692).

Doing a quick search through the MMOCore issue tracker, users have reported it causing problems with many third-party plugins. In particular, this following report is pretty much the problem at hand here: https://git.mythiccraft.io/mythiccraft/mmocore/-/issues/30
