### ISSUE TITLE
supplement with mythic mobs

### ISSUE THREAD

**Issue by UnJavi** [PyvesB/advanced-achievements#983]
:information_source: **I'm trying to create achievements by killing a mythic mob but nothing happens when I kill them, the example they have with the skeletal knight doesn't even work**

* Advanced Achievements version: 
* Minecraft version: 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 
* Spigot username: 

:question: **How do I make achievements with mythic mobs?**

:wrench: **Configuration**

  # Mythic Mobs 'Display' parameter. Change & to §.
  §2SkeletalKnight:
    1:
      Goal: Kill the evil Skeletal Knight.
      Message: §eYou killed a Mythic Mob!
      Name: kills_1_skeletal_night
      DisplayName: Mythic Killer
      Type: rare
  §prueba:
    1:
      Goal: Mata a un esqueleto de pruebas
      Message: &ePrimera sangre
      Name: kills_1_prueba
      DisplayName: En busca de huesos
      Type: normal
````

````

**Comment by PyvesB** [comment]
Please fill out the issue template.
