### ISSUE TITLE
Questions on creating new achievements.

### ISSUE THREAD

**Issue by Redstone-ray** [PyvesB/advanced-achievements#986]
:information_source: 
Hello! I am configuring the plugin and have several questions I'd like to get clear about.

1.  First of all, I see there is a "Type" option that sets the rarity of the achievements. However, the only two levels I know are "normal" and "rare". What are the other options for this, and what does this setting change?
2. What will the GUI look like if I have multiple achievements under the same category set (For example, if I have both breaking 100 ice and breaking 100 dirt, will both achievements appear on the same line in the GUI, or will the second one start on a new line? Does the way I order the achievements in the config file changes how they show up in the GUI?
3. It seems like I must have every section configured for the plugin to function properly. If I'd like to not have any achievements for a certain category (for example, I do not wish to have any achievements for DistanceMinecart), how do I completely disable that section?
4.If I change the config file at a later date to modify the Rewards or goals after some players already achieved that achievement, how would the plugin deal with that situation (Does it take away the achievement from the player, or does it just ignore the players with that achievement already, etc?)
5. Lastly, I am unsure about which part of the message I can use colour code.
```
DistanceBoat:
  200:
    Goal: Travel 200 Blocks with a boat.
    Message: You travelled 200 blocks in a boat!
    Name: distanceboat_200
    DisplayName: Great Sailor
    Type: normal
```
Which of these lines above are allowed to use colour code on?

Thanks for your support, and I anticipate your response!

* Advanced Achievements version: 7.0.1
* Minecraft version: 1.16.5
* Spigot username: Redstone_ray

**Comment by PyvesB** [comment]
Hello @Redstone-ray ! 👋🏻 

>     1. First of all, I see there is a "Type" option that sets the rarity of the achievements. However, the only two levels I know are "normal" and "rare". What are the other options for this, and what does this setting change?

https://github.com/PyvesB/advanced-achievements/wiki/FAQ-(Frequently-Asked-Questions)#1-name-displayname-goal-message-and-type-whats-all-this-about

Use whatever options you want, "normal" and "rare" are just examples.

>     2. What will the GUI look like if I have multiple achievements under the same category set (For example, if I have both breaking 100 ice and breaking 100 dirt, will both achievements appear on the same line in the GUI, or will the second one start on a new line? Does the way I order the achievements in the config file changes how they show up in the GUI?

Reorder the sub-categories in _config.yml_ to change their order in the category GUIs. They will however appear on the same line.

>     3. It seems like I must have every section configured for the plugin to function properly. If I'd like to not have any achievements for a certain category (for example, I do not wish to have any achievements for DistanceMinecart), how do I completely disable that section?

https://github.com/PyvesB/advanced-achievements/blob/855a65a5943df59b0c3fdaa395206f40d7a6beb2/advanced-achievements-plugin/src/main/resources/config.yml#L108

>        4.If I change the config file at a later date to modify the Rewards or goals after some players already achieved that achievement, how would the plugin deal with that situation (Does it take away the achievement from the player, or does it just ignore the players with that achievement already, etc?)

https://github.com/PyvesB/advanced-achievements/wiki/FAQ-(Frequently-Asked-Questions)#6-i-have-changed-the-name-parameter-of-an-achievement-why-do-players-who-had-previously-received-it-no-longer-have-it

>     4. Lastly, I am unsure about which part of the message I can use colour code.
> 
> 
> ```
> DistanceBoat:
>   200:
>     Goal: Travel 200 Blocks with a boat.
>     Message: You travelled 200 blocks in a boat!
>     Name: distanceboat_200
>     DisplayName: Great Sailor
>     Type: normal
> ```

I believe colours will work in `Goal`, `Message`, `DisplayName`. `Name` should follow the format indicated in https://github.com/PyvesB/advanced-achievements/wiki/FAQ-(Frequently-Asked-Questions)#1-name-displayname-goal-message-and-type-whats-all-this-about

Let me know if this helps! 😉
