### ISSUE TITLE
Item given with Name 

### ISSUE THREAD

**Issue by Klotzlutscher** [PyvesB/advanced-achievements#988]
:information_source: **Basic information**

* Advanced Achievements version: 7.0.1
* Minecraft version: 1.16.4 Paper 416
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Klotzlutscher

:question: **Help request**

We had on one Achievement where we get Bucket as a Reward, that needs to have a Special a Name.
Before we updatet this have 100% function and was not a problem.
Now when we get the reward the Bucket is still a Bucket, not a Bucket with Name on it, are we doing something wrong or is it a bug?i know that i can fix it for the moment with an Give command insteat, but think if its a bug its noticable to report.

:wrench: **Configuration**

  100:
    Goal: Befülle Wassereimer.
    Message: §bWasser Wasser Wasser, wir haben Durst!
    Name: §aFlasche-III
    Displayname: §aFlasche-III
    Type: normal
    Reward:
      Command:
        Execute: lp user PLAYER permission set scutilities.usemagicbucket.5 true
        Display: §e5x Aufladungen für endlosen Eimer
      Item: Bucket 1 SecretBucket

https://i.imgur.com/dRxKt2i.png

**Comment by PyvesB** [comment]
Hello @Klotzlutscher ! 👋🏻 

Reward parsing was rewritten in version 7.0.0, it's entirely possible that a bug may have sneaked in. Will try to reproduce in the coming days.

In the meantime, if anyone else notices the same behaviour, do leave a comment (or even try submitting a pull request). 😉

**Comment by PyvesB** [comment]
This was indeed a bug, thanks for reporting. The fix will be released as part of version 7.0.3 of the plugin. 😉
