### ISSUE TITLE
Do you know of a config available that mirrors/replicates the vanilla advancements?

### ISSUE THREAD

**Issue by nerdpower** [PyvesB/advanced-achievements#992]
:information_source: **Basic information**

* Advanced Achievements version: Latest (have not purchased yet)
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes
* Spigot username: nerdpower47

:question: **Help request**
Do you know of someone who has published a config that mirrors the Vanilla Advancements? I would like to turn off Vanilla advancements and only use this plugin. 

:wrench: **Configuration**
None, not installed yet.

````

````

**Comment by PyvesB** [comment]
Hello @nerdpower ! 👋🏻 

I personally don't know of any such config. But I can keep this issue open for a little while, maybe someone will come by with something to share. 😉

**Comment by PyvesB** [comment]
No one has reacted to this in over two months, will close for the time being.
