### ISSUE TITLE
economy suffix

### ISSUE THREAD

**Issue by SirCraftypants** [PyvesB/advanced-achievements#993]
Hi. my rewards appear as 

Rewards:

- receive 500
- receive 100 Experience

when set as 

    Reward:
      Money: 500
      Experience: 1000     

Is there any way i can add my money suffix after the money amount?

**Comment by PyvesB** [comment]
Hello @SirCraftypants ! 👋🏻 

To be honest, I don't understand. You've raised pretty much the exact same issue in the past (#815), received a detailed answer and indicated that you were happy with said answer.

I'll go ahead and close this as duplicate - and also "poor quality" as you've ignored the issue templates and contribution guidelines.
